NCCE/teachcomputing.org

app/components/non_bordered_cards_component/non_bordered_cards_component.scss
app/views/pages/primary-senior-leaders.html.erb
app/views/pages/secondary-senior-leaders.html.erb
app/webpacker/stylesheets/settings/_colors.scss
config/locales/views/pages/primary-senior-leaders/en.yml
config/locales/views/pages/secondary-senior-leaders/en.yml
config/routes.rb
spec/views/pages/primary-senior-leaders.html_spec.rb

* Current Status: Ready for reviewing
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2222
*Adds a primary senior leaders page just like the primary leaders page*

Primary senior leaders pages

---

config/locales/views/pages/primary-senior-leaders/en.yml

Corrects event label and link url

---

app/views/pages/gender-balance.html.erb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2241
updates text

Copy text edit update

---

db/seeds/activities/stem_learning.rb
db/seeds/programmes/secondary-certificate.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2243
* Adds course seeds
* Run `rails db:seed`

2243: Seed courses

---

lib/tasks/detect_unlinked_achievements.rake
lib/tasks/fix_unlinked_achievements.rake
spec/lib/tasks/detect_unlinked_achievements_spec.rb
spec/lib/tasks/fix_unlinked_achievements_spec.rb

* Fix checks for unlinked achievements to take enrolment into account
* Add tests
* N/A

Fix tasks to check for enrolment, add tests

---

.env.defaults
.env.test
app/services/curriculum_client/connection.rb
scripts/setup.sh
spec/rails_helper.rb
spec/requests/dynamics/user_spec.rb

* Ensure test envs are used for local test runs
* Tidy up vars
* N/A

Make sure test envs are used locally

---

app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb

* Current Status: WIP / Ready for review
* Ensure envvar has a default value
N/A

Default value bypass to false

---

app/controllers/certificates/cs_accelerator_controller.rb
app/helpers/tracking_helper.rb
app/views/certificates/cs_accelerator/_achievements.html.erb
app/views/certificates/cs_accelerator/_pathway-switcher.html.erb
app/views/certificates/cs_accelerator/complete.html.erb
app/views/certificates/cs_accelerator/show.html.erb

* Related https://github.com/NCCE/teachcomputing.org-issues/issues/2263
* Add tracking as per issue
* N/A

2263: Add tracking

---

app/helpers/application_helper.rb

* Adds qa to safe redirects
* N/A

Add qa to list of allowed redirects

---

Gemfile

* Fix failing component previews
* N/A

Updates templates (#1666)

---

db/seeds.rb
db/seeds/activities/future_learn.rb
db/seeds/activities/mylearning.rb
scripts/change_activity_codes.rb
scripts/retire_activity_codes.sh
scripts/retired_template_codes_template_uuids.tsv
scripts/undo_retired_activity_codes.sh
scripts/undo_retired_template_codes_template_uuids.tsv

* Review App link(s): https://qa.teachcomputing.org
* Related to https://github.com/NCCE/teachcomputing.org-issues/issues/2299
-  seed 15 courses and add into certificates
- retire 33 courses
In an interactive shell, run
```
./scripts/retire_activity_codes.sh
```

2299 seed moodle courses

---

db/seeds/activities/mylearning.rb

* Related to https://github.com/NCCE/teachcomputing.org-issues/issues/2299 
Fix 2 breaking typos in the new mylearning activity seed script

Fix bugs in mylearning activity seeds

---

db/seeds/activities/preprod_achiever_courses.rb

This test course is only visible on preprod Dynamics
* Review App link(s): https://qa.teachcomputing.org/courses/OC124/ncce-f2f-course

Seed preprod template 'NCCE F2F Course'

---

app/controllers/courses_controller.rb
app/views/courses/_aside-booking.html.erb
app/views/dashboard/_achievement_list.html.erb

* Current Status:  Ready for front-end & tech review
Issue list (checked off if addressed in this PR)

Respond to UAT of support for online Moodle MyLearning courses

---

Gemfile.lock
app/controllers/concerns/curriculum/rateable.rb
app/services/curriculum_client/connection.rb
app/services/curriculum_client/queries/base_query.rb
app/services/curriculum_client/queries/key_stage.rb
app/services/curriculum_client/queries/lesson.rb
app/services/curriculum_client/queries/rateable_query.rb
app/services/curriculum_client/queries/redirect.rb
app/services/curriculum_client/queries/unit.rb
app/services/curriculum_client/queries/year_group.rb
app/services/curriculum_client/request.rb
spec/requests/curriculum/lessons/show_spec.rb
spec/services/curriculum_client/connection_spec.rb
spec/services/curriculum_client/request_spec.rb
spec/support/curriculum/curriculum_stubs.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2271
* Fire a routing error (standard 404)
* Improves error handling on connection errors
* remove complex (to implement) and unnecessary test step
* Factor out unused 'context' parameter
* N/A

2271: Tidy up curriculum error handling

---

app/views/landing_pages/_dedicated_pages.html.erb

Wording edit

---

app/controllers/auth_controller.rb
config/initializers/sentry.rb

* Review App link(s): https://qa.teachcomputing.org
- [Report auth/callback 404s to Sentry (hopefully)](https://github.com/NCCE/teachcomputing.org/commit/1645e0aeee23d2284dbda209fbe8012190dd2145)
- [Turn on Sentry in qa.teachcomputing.org](https://github.com/NCCE/teachcomputing.org/commit/d5928266c59b9b002e882fa4d94d2d15a0a73828)

Instrument auth callback 404s

---

db/migrate/20230323173657_rename_three_primary_courses.rb
db/schema.rb
db/seeds/activities/stem_learning.rb

closes https://github.com/NCCE/teachcomputing.org-issues/issues/2332
@maddyjoe would you like Storm or RPF to deploy this? And are you OK with someone changing these titles now (rather than waiting until NCCE2)?

Update titles of CP008 CP456 and CP005

---

db/migrate/20230328121836_update_hubs.rb
db/schema.rb

* Current Status: ready for tech review
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2331
- tested in QA https://qa.teachcomputing.org/courses/hubs/30c44ca3-4eca-ed11-b595-002248c6bd96
Update hubs for NCCE2 (4 new, 6 destroyed)
~this will merge into the rebrand-styles branch for ease of deployment (the Heroku release task will run the migration automatically)~

Update hubs for NCCE2 (4 new, 6 destroyed)

---

app/components/related_links_component/related_links_component.scss
app/views/landing_pages/_champions-aside.html.erb
app/views/pages/certification/_statement.html.erb
app/webpacker/stylesheets/components/cms/_shared.scss

* Fixes issue with white links on some pages

update link colors, fix subject-practitioners page images

---

config/routes.rb
spec/requests/api/users_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2352
*http Verbs changed*

Change http verbs

---

app/views/hubs/index.html.erb
app/views/landing_pages/_support.html.erb
config/locales/views/hubs.en.yml

* Ready for review
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2364
*Updates contact form link url*

Contact form link update

---

app/views/pages/enrolment/secondary-certificate.html.erb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2365
**Adds link to ghost page in explore section**

Adds link to Ghost page

---

lib/tasks/achiever.rake
lib/tasks/add_new_academic_year_badges_and_update_enabled_badges.rake
lib/tasks/create_badge_records.rake
lib/tasks/refresh_achiever_local_templates.rake
lib/tasks/update_certificate_data.rake
lib/tasks/update_primary_data.rake
spec/lib/tasks/achiever_spec.rb
spec/lib/tasks/add_new_academic_year_badges_and_update_enabled_badges_spec.rb
spec/lib/tasks/create_badge_records_spec.rb
spec/lib/tasks/refresh_achiever_local_templates_spec.rb
spec/lib/tasks/update_certificate_data_spec.rb
spec/lib/tasks/update_primary_data_spec.rb
spec/support/achiever/achiever_stubs.rb

* Current Status: Ready for  review
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2380
Sets of tests to cover previously untested rake files

Tests to cover previously untested rake files

---

public/robots.txt

* Current Status: Ready for  review
- Added disallow rules to stop semrush from crawling the site
[ ref: https://www.semrush.com/bot/ ]
Nothing - to my knowledge

Added multiple disallow rules for semrush to robots.txt file

---

app/views/pages/pedagogy.html.erb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2419
*text edit on pedagogy page*

Edits pedagogy text

---

db/seeds/activities/stem_learning.rb

- closes [#2435](https://github.com/NCCE/teachcomputing.org-issues/issues/2435)
- closes [#2436](https://github.com/NCCE/teachcomputing.org-issues/issues/2436)
- closes [#2437](https://github.com/NCCE/teachcomputing.org-issues/issues/2437)
new courses:
- CP256
- CP257
- CP403
Inform Andy Smith (CST) that the courses are ready to publish on Dynamics

Seed 3 new live non-certificate courses

---

.env.test
app/helpers/navigation_helper.rb
app/services/feature_flag_service.rb
config/routes.rb
spec/services/feature_flag_service_spec.rb

* Current Status: Ready to merge to your branch @nyashamaphosa 
- hide the nav bar entry
- hide the route to the page
In order to continue developing these pages, in your dev environment you'll want to add this to `.env`
```
FLAG_IBELONG_PROGRAMME=on
```
and restart your web server for example with `touch tmp/restart.txt`

I Belong feature flag for public page

---

app/webpacker/stylesheets/components/_flex.scss

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2416
*Resolves text wrapping issue on mobile view*

Mobile view text 

---

app/helpers/navigation_helper.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2452
Switch Nav elements

switches positioning of nav elements

---

db/seeds/activities/stem_learning.rb

* Current Status: Ready review
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2445
Seeds courses

course seeding

---

app/webpacker/stylesheets/components/programmes/_ihavedonethis.scss
db/seeds/activities/stem_learning.rb

* 
Previously, button the text of the button would go white making it unseeable. This change makes the text black on hover, so it can now be seen.

Updated ihavedonethis button hover state

---

db/seeds/activities/mylearning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2455
Seeds Courses

seeds courses

---

.circleci/config.yml
app/views/certificates/cs_accelerator/show.html.erb
db/seeds/pathways/cs_accelerator.rb

* Current Status: Ready for (front-end) review
Updated CSA copy

Update CSA copy

---

db/seeds/activities/mylearning.rb
db/seeds/pathways/primary_certificate.rb
db/seeds/pathways/secondary_certificate.rb

Seeding CO230, adding CO230, CO040, and CO042 to pathways

Seeding courses CO230 and adding CO040 and CO042 to pathways

---

db/seeds/activities/mylearning.rb
db/seeds/pathways/secondary_certificate.rb

Seeding courses

---

app/views/pages/terms-conditions.html.erb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2418
Amends Tcs and cs text

Amends text

---

db/seeds/activities/stem_learning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2464
Seed an Activity

seeds course

---

app/services/achiever/course/age_group.rb
spec/services/achiever/course/age_group_spec.rb

* Closes [*add issue number or delete*](https://github.com/NCCE/teachcomputing.org-issues/issues/2474)
Adds Post 16 as an age group

Add Post 16 as an age group

---

app/helpers/external_link_helper.rb
app/helpers/s3_link_helper.rb
db/seeds/activities/community.rb
db/seeds/enrichment_groupings/primary_certificate.rb
db/seeds/enrichment_groupings/secondary_certificate.rb
spec/helpers/external_link_helper_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2469
- Added links to webinars
(check git message for some implementation details)

Added webinar links to enrichment descriptions

---

app/helpers/navigation_helper.rb
config/routes.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2466
- reorders items in navigation
- adds AI page into navigation
- It should be noted that we still have separate GCSE and A Level Isaac pages as they've not been merged into one yet

Reordered navigation entries and added AI page

---

app/views/pages/enrolment/i_belong.html.erb
spec/views/pages/enrolment/i_belong.html_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2473
- Alters IB Copy
I've just replaced the PDF in S3 so no code change is required there

Updated IB copy

---

Gemfile
Gemfile.lock
app/components/cpd_course_component.rb
app/components/progress_bar_component.rb
app/models/programme_activity_grouping.rb
app/views/certificates/primary_certificate/_achievement_list.html.erb
app/views/certificates/secondary_certificate/_achievement_list.html.erb
config/environments/development.rb
spec/models/programme_activity_grouping_spec.rb

Remove N+1 queries from secondary and primary pages

---

app/jobs/cs_accelerator_enrolment_transition_job.rb
app/jobs/update_user_assessment_attempt_from_class_marker_job.rb
app/models/programmes/cs_accelerator.rb
app/models/programmes/secondary_certificate.rb
spec/jobs/cs_accelerator_enrolment_transition_job_spec.rb
spec/jobs/update_user_assessment_attempt_from_class_marker_job_spec.rb
spec/models/programmes/secondary_certificate_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2480
Secondary certificate now require CSA

Secondary certificate requires CSA to be completed

---

app/controllers/certificates/i_belong_controller.rb
app/services/achiever/course/delegate.rb
app/services/achiever/course/occurrence.rb
app/services/achiever/course/template.rb
app/services/achiever/request.rb
app/views/certificates/i_belong/_achievement_list.html.erb
db/seeds/activities/stem_learning.rb
db/seeds/programme_activity_groupings/i_belong.rb
spec/requests/certificates/i_belong_dashboard_spec.rb
spec/services/achiever/course/occurrence_spec.rb
spec/services/achiever/course/template_spec.rb
spec/services/achiever/request_spec.rb
spec/support/achiever/achiever_stubs.rb

…ulled from
* Review App link(s): https://teachcomputing-pr-1805.herokuapp.com/
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2465
- Adds FD022 course from PDLD
- Makes FD022 course part of IB

Include PDL in IB course

---

app/components/community_activity_list_component.rb
app/components/community_activity_list_component/community_activity_list_component.html.erb
app/components/community_activity_list_component/community_activity_list_component.scss
app/views/certificates/i_belong/_achievement_list.html.erb
app/views/certificates/primary_certificate/_achievement_list.html.erb
app/views/certificates/secondary_certificate/_achievement_list.html.erb
app/webpacker/javascript/controllers/community_activity_list_controller.js
spec/components/community_activity_list_component_spec.rb

* Review App link(s): https://teachcomputing-pr-1810.herokuapp.com/certificate/primary-certificate
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2409
Adds expanders as per figma to page

Reduce page length with expander

---

db/seeds/activities/stem_learning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2493
Seeded courses in https://docs.google.com/spreadsheets/d/1fCUt9z55gJUIKklWu0Rr6aW3mnAXeeV8TRQW8grX6Nw/edit#gid=0 rows 191 to 198

Added new CPDs

---

app/views/a_level_mailer/completed.html.erb
app/views/a_level_mailer/completed.text.erb
app/views/a_level_mailer/welcome.html.erb
app/views/a_level_mailer/welcome.text.erb
previews/mailers/a_level_mailer_preview.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2472
Adds emails for a level

Added AL mailer content

---

app/views/pages/enrolment/cs_accelerator.html.erb
db/seeds/activities/mylearning.rb
db/seeds/pathways/cs_accelerator.rb
db/seeds/pathways/secondary_certificate.rb
db/seeds/pathways_helper.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2497
Updates CSA pathway seeds to the new format and adds all the new courses to match the pathways

Updated CSA to include all the activities listed in PDFs

---

app/services/achiever/course/template.rb

Ensures that searches via template_no are downcased

Ensure that templates are searched using the appropriate case

---

app/services/achiever/course/template.rb
db/schema.rb

Search for templates without case

---

db/seeds/activities/stem_learning.rb

Seeded CP502 CP298 CP457

---

db/seeds/activities/stem_learning.rb

Update CP413 to not online

---

app/services/achiever/course/template.rb

* Related to reported problem with course list showing only a single course
Added debug logging to course caching method
Deletes cache if fewer than 10 courses were cached (forcing a rewrite on next request)
Monitor reported exceptions to understand duration of original problem.

Mitigation for caching too-small course list

---

app/jobs/certificate_pending_transition_job.rb
app/jobs/update_user_assessment_attempt_from_class_marker_job.rb
app/models/programme.rb
spec/jobs/certificate_pending_transition_job_spec.rb
spec/jobs/update_user_assessment_attempt_from_class_marker_job_spec.rb
spec/models/programme_spec.rb

Fixes the transition to pending job to support a level.

Fix a level not transitioning to complete on class marker finish

---

app/jobs/schedule_certificate_completion_job.rb
app/models/programme.rb
app/models/programmes/i_belong.rb
app/models/state_machines/user_programme_enrolment_state_machine.rb
spec/factories/user.rb
spec/models/user_programme_enrolment_spec.rb
spec/views/certificates/i_belong/complete_spec.rb

Refactor certificate name assignment into one central place

Refactor certificate name assignment

---

db/seeds/activities/stem_learning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2520
Adds CP505.
QA: It should be visible in the courses list and on the A-Level programme dashboard

Added CP505

---

app/components/community_activity_component/community_activity_component.html.erb
app/components/community_activity_component/community_activity_component.scss
app/webpacker/images/icons/submit_evidence_chevron.svg

* Review App link(s): https://teachcomputing-pr-1856.herokuapp.com/certificate/i-belong
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2507
Altered the submit evidence button to show "continue editing" after a draft has been added. Shows a right chevron rather than a down chevron.

Added continue editing button

---

config/locales/views/pages/isaac_computer_science/en.yml

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2506
Minor tweaks to the copy on the page as per the designs here - https://www.figma.com/file/IvqgygMrtttMZ829PL0Yva/IsaacPageOnTC-300823?type=design&node-id=0-1&mode=design

updated text on isaac computer science page

---

app/models/programme_activity_grouping.rb
db/seeds/activities/community.rb
db/seeds/activities/stem_learning.rb
db/seeds/pathways/primary_certificate.rb
db/seeds/pathways/secondary_certificate.rb
db/seeds/programme_activity_groupings/primary_certificate.rb
db/seeds/programme_activity_groupings/secondary_certificate.rb

Ensure activities are current in completions

---

README.md
app/controllers/api/users_controller.rb
app/controllers/auth_controller.rb
app/mailers/a_level_mailer.rb
app/mailers/achievement_mailer.rb
app/mailers/application_mailer.rb
app/mailers/assessment_mailer.rb
app/mailers/cs_accelerator_mailer.rb
app/mailers/i_belong_mailer.rb
app/mailers/new_badge_mailer.rb
app/mailers/primary_mailer.rb
app/mailers/secondary_mailer.rb
app/models/user.rb
spec/mailers/application_mailer_spec.rb
spec/models/user_spec.rb

This PR removes the unique constraint on emails.

Allow users to be duplicated

---

app/jobs/issue_badge_job.rb
app/services/programmes/user_enroller.rb
db/seeds/activities/stem_learning.rb
db/seeds/enrichment_groupings/secondary_certificate.rb
spec/jobs/issue_badge_job_spec.rb
spec/services/programmes/user_enroller_spec.rb

Fix credly badge assignments

---

db/seeds/activities/stem_learning.rb

Updated CP294 and add CP406

---

db/seeds/activities/stem_learning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2543
Seeding new courses are requested on 04/12/2023

Adding in the new courses as requested

---

app/services/achiever/course/occurrence.rb
app/services/achiever/course/occurrence_details.rb
app/services/achiever/course/template.rb
spec/services/achiever/course/occurrence_details_spec.rb
spec/support/achiever/achiever_stubs.rb

Add Computing Cluster CPDs to those that are queryed

---

app/views/components/_footer.html.erb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2527
A link added to the footer menu, as well as a link update that has already been completed in the safeguarding page

added a link to the safeguarding pagew in the footer

---

app/components/site_search_component/site_search_component.scss
app/components/site_search_component/site_search_component_controller.js
app/jobs/searchable_page_indexing_job.rb
app/lib/searchable_site_pages.rb
app/models/searchable_pages/course.rb
app/models/searchable_pages/site_page.rb
app/services/achiever/course/template.rb
app/services/curriculum_client/queries/key_stage.rb
config/routes.rb
spec/factories/searchable_pages/course.rb
spec/factories/searchable_pages/site_page.rb
spec/jobs/searchable_page_indexing_job_spec.rb
spec/lib/searchable_site_pages_spec.rb
spec/models/searchable_pages/course_spec.rb
spec/models/searchable_pages/site_page_spec.rb
spec/requests/certificates/pathways_spec.rb
spec/requests/enrichment_spec.rb

Add all other pages to site search

---

db/seeds/enrichment_groupings/primary_certificate.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2536
Replace the Do Your Bit logo with the Microbit logo

replace microbit logo

---

app/jobs/issue_badge_job.rb
app/models/programme.rb
app/models/state_machines/achievement_state_machine.rb
app/models/state_machines/assessment_attempt_state_machine.rb
app/services/programmes/user_enroller.rb
spec/jobs/issue_badge_job_spec.rb
spec/models/programme_spec.rb

Credly badges will now be fired for A Level successful completions

---

app/components/external_link_card_component.rb
app/components/external_link_card_component/external_link_card_component.html.erb
app/components/external_link_card_component/external_link_card_component.scss
app/components/mixed_cards_component.rb
app/components/mixed_cards_component/mixed_cards_component.html.erb
app/components/mixed_cards_component/mixed_cards_component.scss
app/services/curriculum_client/queries/unit.rb
app/views/curriculum/units/show.html.erb
spec/components/external_link_card_component_spec.rb
spec/components/mixed_cards_component_spec.rb
spec/support/curriculum/curriculum_schema.json
spec/support/curriculum/responses/unit.json
spec/support/curriculum/views/unit.json

* Closes: https://github.com/NCCE/teachcomputing.org-issues/issues/2530
* 
Added the new card for external links to the unit page, this has been done as a mixed component that supports files and external links so ordering can be changed easily. Created a component to support the external link in the style of a file card so they look similar. Also made the changes to the GRAPHQL query to pull the new digital summative assessment from curriculum.

Digital Summative Assessment Button

---

app/components/community_activity_component/community_activity_component.html.erb

Use the correct titles

---

app/helpers/navigation_helper.rb
config/locales/views/pages/secondary-certification/en.yml
spec/views/components/_header_spec.rb

* Resolves https://github.com/NCCE/teachcomputing.org-issues/issues/2545

Requested text changes to certificates

---

config/locales/views/pages/secondary-senior-leaders/en.yml

* Resolves https://github.com/NCCE/teachcomputing.org-issues/issues/2546
Fixing incorrect link

Fixing incorrect link

---

config/locales/views/pages/secondary-senior-leaders/en.yml

* Current Status: WIP / Ready for review
* Resolves https://github.com/NCCE/teachcomputing.org-issues/issues/2546

Finally got the right link on this one

---

spec/factories/programmes/cs_accelerator.rb
spec/requests/hubs/index_spec.rb
spec/support/geocoder.rb
spec/system/pages/static_pages_spec.rb

Few small test suite updates
* Current Status:  Ready for tech review
Testing of the hubs controller and also adding in some testing for the subject knowledge page as these were showing as pending

Hubs controller testing and replacing pending test section with some tests

---

db/seeds/activities/stem_learning.rb

* Review App link(s): https://teachcomputing-pr-1886.herokuapp.com/courses
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2553
Changed CP352 to CP552
There is no good way for us to review this change so a check of the code change will have to be sufficient

Updated CP352 to CP552

---

app/views/cms/articles.html.erb
app/webpacker/stylesheets/components/cms/_shared.scss
app/webpacker/stylesheets/components/pages/_news.scss

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2562
new classes have been added in order to pull in the correct styles for stacking content on mobile

added classes to match the ghost blog, added missing styles

---

config/initializers/omniauth.rb
spec/omniauth/strategies/stem_spec.rb

This reverts commit 63de5895261c54fc2e441f5194884e83a087e77b, reversing changes made to 9f900b776504ead3add165ed48ba0ede4ba7c6b3.

Revert "Merge pull request #1889 from NCCE/2561/update-login-logic"

---

db/seeds/activities/stem_learning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2568
Adding CP506

Seeding CP506

---

app/mailers/application_mailer.rb
previews/mailers/a_level_mailer_preview.rb
previews/mailers/achievement_mailer_preview.rb
previews/mailers/assessment_mailer_preview.rb
previews/mailers/cs_accelerator_mailer_preview.rb
previews/mailers/i_belong_mailer_preview.rb
previews/mailers/new_badge_mailer_preview.rb
previews/mailers/primary_mailer_preview.rb
previews/mailers/secondary_mailer_preview.rb

Adds in mailers for IB inactivity mailers

Add previews for i belong mailers

---

db/seeds/activities/community.rb
db/seeds/pathways/primary_certificate.rb

* Review App link(s): https://teachcomputing-pr-1885.herokuapp.com/
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2538
Removes extra activities from primary
- Review pathways on enrichment pages and ensure they don't include any extra activities https://teachcomputing-pr-1885.herokuapp.com/primary-enrichment
-

Removed extra activities

---

app/models/programme_activity_grouping.rb
db/seeds/programme_activity_groupings/primary_certificate.rb
spec/models/programme_activity_grouping_spec.rb

* Review App link(s):
Adds in an extra test case
Also moved an activity to legacy that should have been legacy

Added test case to ensure legacy activities don't count

---

db/seeds/activities/assessment.rb
db/seeds/activities/community.rb
db/seeds/activities/mylearning.rb
db/seeds/activities/stem_learning.rb
db/seeds/enrichment_groupings/primary_certificate.rb
db/seeds/enrichment_groupings/secondary_certificate.rb
db/seeds/pathways/primary_certificate.rb
db/seeds/pathways/secondary_certificate.rb
db/seeds/programme_activity_groupings/a_level.rb
db/seeds/programme_activity_groupings/i_belong.rb
db/seeds/programme_activity_groupings/primary_certificate.rb
db/seeds/programme_activity_groupings/secondary_certificate.rb
db/seeds/programmes/a_level.rb
db/seeds/programmes/cs_accelerator.rb
db/seeds/programmes/i_belong.rb
db/seeds/programmes/primary-certificate.rb

Also changed to be more noisy when a save fails
Updates all Primary/Secondary/IBelong/ALevel CPDs to have the correct number of credits.
Also calls .save! rather than .save so we get some feedback if a record fails to update

Update seeds to have correct counts of credits

---

config/initializers/omniauth.rb

Added logger to capture the response for schools from IDP

Adding logger to see if school is updated in IDP

---

config/initializers/omniauth.rb

Adding logger to check if organisationNumber has been updated

Logging Org No

---

app/jobs/kick_off_emails_job.rb

Fix datetime

---

db/seeds/activities/stem_learning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2581
Adding missing save off the seed for CP506

Fixing seed issue

---

app/jobs/auto_enrol_job.rb
spec/jobs/auto_enrol_job_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2587
Fixing bug due to nil variable

Fixing bug in auto enrolment for subject knowledge

---

app/views/i_belong_mailer/completed.html.erb
app/views/i_belong_mailer/completed.text.erb
spec/mailers/i_belong_mailer_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2590
Adding link to press pack to the completion email, and adding tests to ensure inclusion

I Belong Press Pack in completion email

---

db/seeds/activities/community.rb
db/seeds/pathways/secondary_certificate.rb
db/seeds/programme_activity_groupings/secondary_certificate.rb

* Review App link(s): https://teachcomputing-pr-1942.herokuapp.com/
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2589
Updating pathway to match the supplied PDF

Updates to Championing diversity and inclusion pathway

---

db/seeds/programme_activity_groupings/secondary_certificate.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2606
Fixing mix up with course changes from the other week

Fixing mixup in legacy course definition

---

.circleci/config.yml

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2611
Swapping chrome setup as per suggestion on github to resolve issue

Fix circleCI Chrome Driver

---

app/helpers/enrolment_helper.rb
app/views/pages/_inspire_with_computing_ambassador.html.erb
app/views/pages/primary-senior-leaders.html.erb
app/views/pages/secondary-senior-leaders.html.erb
app/webpacker/stylesheets/components/pages/_inspire_with_computing_ambassador.scss
config/locales/views/pages/primary-senior-leaders/en.yml
config/locales/views/pages/secondary-senior-leaders/en.yml
config/routes.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2605
* Review https://teachcomputing-pr-1954.herokuapp.com/
Link changed on non-gcse page, and fixing a few typos

Fixing link issue and some typos

---

db/seeds/activities/stem_learning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2625
- Seeding CP407

Seeding CP014

---

app/views/pages/enrolment/i_belong.html.erb
app/webpacker/stylesheets/application.scss
app/webpacker/stylesheets/components/_video.scss
spec/views/pages/enrolment/i_belong.html_spec.rb

Add video to i belong page

---

db/seeds/activities/stem_learning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2627
* Seeded CP268

Seeding CP268

---

db/seeds/activities/stem_learning.rb

Reverts NCCE/teachcomputing.org#1987
Wrong credit amount added, should be 160 as not in CSA programme.

Revert "Seeding CP268"

---

db/seeds/activities/stem_learning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2627
* Course reseeded now with the correct number of credits

CP268 now with the correct credit count

---

db/seeds/activities/mylearning.rb

* Current Status: Ready for tech
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2630
Adding CP408 online course

Seeding CP408

---

.devcontainer/devcontainer.json
app/models/activity.rb
db/seeds/activities/stem_learning.rb
spec/models/activity_spec.rb

Adding test cases and updating seed
Updates need to be done in the console before deploying this, to prevent courses being double seeded
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2628
- Making the setter automatically downcase the ID
- Updated the seed file
The ID's listed in the issue need to be downcased **before** deployment to production otherwise the seed will generate a second copy of the course.

Updating setter to downcase Stem Course Template No

---

db/seeds/activities/mylearning.rb
db/seeds/activities/stem_learning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2634
CP408 was sent to us are online, should be remote. This will convert it to the correct type

Reseed CP408

---

db/seeds/activities/stem_learning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2637
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2638
- Adding CP015
- Adding CP016

Seeding cp015 and cp016

---

.env.defaults
docker-compose.yml

Requested by IT support
* Current Status: Ready for tech
Requested by IT support to secure local redis instances

Enabled password on local Redis Instance

---

app/components/banner_component/banner_component.scss

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2653
- Removed incorrect CSS colour

Removing incorrect grey font on the banner

---

app/components/bordered_cards_component/bordered_cards_component.scss
app/views/pages/primary-toolkit.html.erb
app/views/pages/secondary-toolkit.html.erb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2654
Spotted an issue with the i-belong clickable banner on mobile view.
Also fixed the problem with single card per row being reduced to 50% width when in tablet view

Fixing the issue we found with the clickable i-belong banner

---

app/assets/stylesheets/administrate/fields/achievement_list.scss
app/views/fields/achievement_list_field/_show.html.erb
spec/views/fields/achievement_list_field/_show.html_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2655
Added CSS to break long URL.
Converting new lines into line breaks.
Added tests to cover line breaks.

Fixing display issues with long URLs, new line replaced with break rules.

---

spec/helpers/curriculum_helper_spec.rb
spec/models/programmes/cs_accelerator_spec.rb
spec/models/user_programme_enrolment_spec.rb

Additional test coverage for some of the tasks under Sprint 18

Improvements to test coverage

---

app/models/enrichment_entry.rb
db/seeds/enrichment_groupings/primary_certificate.rb
db/seeds/enrichment_groupings/secondary_certificate.rb
spec/models/enrichment_entry_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2659
- Removed links from primary enrichment seeds
- Removed links from secondary enrichment seeds
- Removed validation for body content on enrichment_entry model
- Removed body content from single primary enrichment body seed

Removed links from primary enrichment page seeds

---

db/seeds/enrichment_groupings/primary_certificate.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2678
- Removed links from primary enrichment seed

Removed links for primary enrichment page

---

app/models/programme.rb
app/models/programmes/a_level.rb
app/models/programmes/i_belong.rb
app/services/achiever/course_filter.rb
spec/models/programme_spec.rb
spec/models/programmes/a_level_spec.rb
spec/models/programmes/i_belong_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2657
- Added boolean flag onto filters on programmes model
- Added false for I Belong and A Level
- Added rpsec test to check for true on method

Added boolean flag for filters onto programmes

---

db/seeds/enrichment_groupings/secondary_certificate.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2685
- Removed cyber centurion from secondary enrichment seed file

Removed cyber centurion from secondary certificate seed

---

config/locales/views/pages/home/en.yml

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2690
Some small copy changes to the homepage

Updating home page copy

---

app/views/pages/tech-careers-videos.html.erb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2691
Adding title to tech careers video page

Adding in page title

---

config/locales/views/pages/tech-careers-videos/en.yml

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2695
Fixing typo in header

Fixing typo in the tech careers video title

---

app/helpers/external_link_helper.rb
app/views/i_belong_mailer/pending.html.erb
app/views/i_belong_mailer/pending.text.erb
spec/helpers/external_link_helper_spec.rb
spec/mailers/i_belong_mailer_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2675
* PR app https://teachcomputing-pr-2042.herokuapp.com/
Updated pending email text for i-belong

Updating the text on the i-belong pending email

---

db/seeds/activities/stem_learning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2697
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2699
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2700
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2698
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2701
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2702
Added course seeds for the following:
- CP511
- CP513
- CP512
- CP515
- CP516
- CY312

2697 course seed cp511

---

db/seeds/activities/stem_learning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2708
Added course seed for CP514

Added course seed CP514

---

app/views/primary_mailer/auto_enrolled.text.erb
app/views/secondary_mailer/auto_enrolled.html.erb
app/views/secondary_mailer/auto_enrolled.text.erb
app/views/secondary_mailer/inactive_prompt.text.erb
spec/mailers/i_belong_mailer_spec.rb
spec/mailers/primary_mailer_spec.rb
spec/mailers/secondary_mailer_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2667
Increasing test coverage to ensure all mailer methods are in the test suite
Added into a couple of text based views that were missing

Improve mailer test coverage

---

db/seeds/activities/stem_learning.rb

Remove incorrect seed CY312
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2710
- Added course seed CP267
- Removed incorrect course seed CY312

Added course seed CP267

---

app/fields/state_picker_field.rb
app/views/fields/state_picker_field/_index.html.erb

Fix to ensure that staging user programme enrolments that are missing users do not throw exceptions

Fix for missing user on staging - guard added

---

spec/jobs/issue_badge_job_spec.rb

Adding in testing specifically to check the difference between face 2 face activities versus community, after reports (from months back, so likely fixed previously) that users were getting badges from just doing community activities
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2717
Added specific testing for f2f versus community to ensure badges are allocated correctly based on activity type

Adding extra testing for badges

---

app/components/curriculum_video_component/curriculum_video_component.html.erb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2723
- Moved ncce-button inside a div in the curriculum video component to keep it aligned below the text

Moved ncce-button into div to keep alignment

---

app/components/curriculum_video_component/curriculum_video_component.html.erb
app/components/curriculum_video_component/curriculum_video_component.scss

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2724
- Moved the text and image on the details section into separate divs to maintain alignment and handle longer strings of text

Text and image alignment on curriculum video component

---

app/components/featured_blog_posts_component.rb
app/components/seo_block_component.rb
app/helpers/cms_helper.rb
app/services/cms/models/seo.rb
app/services/cms/providers/strapi/factories/model_factory.rb
app/services/cms/providers/strapi/factories/parameter_factory.rb
app/services/ghost_to_strapi.rb
spec/components/featured_blog_posts_component_spec.rb
spec/support/cms/providers/strapi/strapi_stubs.rb
spec/support/ghost/ghost_stubs.rb
spec/views/cms/resource.html_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2687
- Adds support for "featured" blog posts, and updates the homepage component accordingly
- Adds the option for images on SEO blocks
- Fixed a few bugs and improved the testing

2687 add new feature to strapi from comms feedback

---

db/seeds/activities/stem_learning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2732
- Added course seed for CP019

Course Seed CP019

---

db/seeds/activities/stem_learning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2743
- Added course seed CP418

Course Seed CP418

---

app/jobs/achiever/fetch_users_completed_courses_from_achiever_job.rb
spec/jobs/achiever/fetch_users_completed_courses_from_achiever_job_spec.rb

* Related to https://github.com/NCCE/teachcomputing.org-issues/issues/2788
Adding in exception handling to the fetch users job, in the hope that helps diagnose the issues around auto-enrolment

Trying to resolve issues around auto-enrolment

---

db/seeds/activities/stem_learning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2779
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2780
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2781

Seeding CP507, CP517, CP518

---

app/components/pagination_component.rb
app/components/pagination_component/pagination_component.html.erb
app/views/searches/show.html.erb
spec/components/pagination_component_spec.rb
spec/system/site_search_spec.rb

* Review App link(s): https://teachcomputing-pr-2081.herokuapp.com/search?q=computing
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2771
- Creation of a new pagination component using the GovUK front end component
- Replacing the pagination on search pages
- Created testing for pagination component and updated other tests that used old pagination system

Create new pagination system

---

app/views/pages/impact-and-evaluation.html.erb
config/locales/views/pages/impact-and-evaluation/en.yml
spec/views/pages/impact-and-evaluation.html_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2789
- Added the new card onto the research and curriculum section of the page
- Added title, text and date into locale
- Added tests to cover the new card

Added new card onto impact and evaluation page

---

app/jobs/achiever/fetch_users_completed_courses_from_achiever_job.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2796
Fixed typo in error handling code

Fixing typo in error handling code

---

.circleci/config.yml

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2802
- Updated Chrome version for use in Circle CI pipeline

Update Chrome version on circle ci config

---

db/seeds/activities/stem_learning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2804
- Added course seed CP508

Course Seed CP508

---

db/seeds/activities/stem_learning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2806
- Added course seed CP410

Course seed CP410

---

app/views/cms/collection.html.erb
spec/views/cms/collection.html_spec.rb

* Review App link(s): https://teachcomputing-pr-2106.herokuapp.com/blog
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2816
Replaced old version of pagination with the new one

Adding pagination into strapi collection view

---

config/sitemap.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2822
- Updated logic to get units associated with each key stage on curriculum to add to the sitemap.

Fix sitemap inclusions for curriculum

---

db/seeds/activities/mylearning.rb
db/seeds/activities/stem_learning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2826
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2825
- Added course seed CP442
- Added course seed CP427

Course seed CP442 & CP427

---

app/components/course_grid_component/course_grid_component.html.erb
app/helpers/careers_helper.rb
app/helpers/external_link_helper.rb
app/views/certificates/i_belong/complete.html.erb
app/views/pages/_i_belong_banner.html.erb
app/views/pages/primary-senior-leaders.html.erb
app/views/pages/primary-toolkit.html.erb
app/views/pages/school_trusts.html.erb
config/locales/views/pages/home/en.yml
config/locales/views/pages/primary-senior-leaders/en.yml
config/locales/views/pages/primary-toolkit/en.yml
config/locales/views/pages/secondary-toolkit/en.yml
spec/helpers/external_link_helper_spec.rb
spec/views/certificates/i_belong/complete_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2810
- Added I belong banner to primary-teachers and primary-senior-leaders page
- Copy changes on various pages, banners and cards in line with specification document

PIB - Implement I belong copy changes across site

---

app/helpers/external_link_helper.rb

* Related https://github.com/NCCE/teachcomputing.org-issues/issues/2811 
- Updated URL for external helper method

Updating reference for Structuring evidence guidance to new location

---

app/components/cpd_course_item_component/cpd_course_item_component.html.erb
app/components/cpd_course_item_component/cpd_course_item_component.scss
app/controllers/certificates/a_level_controller.rb
app/controllers/certificates/cs_accelerator_controller.rb
app/controllers/certificates/i_belong_controller.rb
app/controllers/certificates/primary_certificate_controller.rb
app/controllers/certificates/secondary_certificate_controller.rb
app/jobs/issue_cpd_badge_job.rb
spec/components/cpd_course_item_component_spec.rb
spec/requests/certificates/a_level_dashboard_spec.rb
spec/requests/certificates/i_belong_dashboard_spec.rb
spec/requests/certificates/primary_certificate/show_spec.rb
spec/requests/certificates/secondary_certificate/show_spec.rb
spec/support/credly/credly_stubs.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2815
- Fixing issue where book now button still showed when in progress or completed. 
- Added some improved error handling for the cpd badge job
- Adding exception handling on dashboard for if Credly goes down

Improve badge handling, fixing bug with book now button always showing

---

.circleci/config.yml

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2848
- Update circleci config.yml to use latest version of Google Chrome 128.0.6613.84

Update circle ci config to latest version of Google Chrome

---

db/seeds/activities/community.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2850
Fixing incorrect reference in seed file to old I Belong handbook

Fix incorrect reference in seed file to I Belong handbook

---

db/seeds/enrichment_groupings/primary_certificate.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2851
- Added I belong flag onto enrichment activities in line with documentation on linked ticket.
- Moved some enrichment activities across from secondary to primary relating to I belong

PIB - Add I belong flag to enrichment activities

---

app/components/dashboard_programme_activity_group_section_component.rb
app/components/dashboard_programme_activity_group_section_component/dashboard_programme_activity_group_section_component.html.erb
app/models/programmes/i_belong.rb
app/views/certificates/i_belong/_achievement_list.html.erb
app/views/pages/enrolment/i_belong.html.erb
db/seeds/activities/community.rb
db/seeds/programme_activity_groupings/i_belong.rb
spec/components/cpd_course_item_component_spec.rb
spec/components/cpd_course_list_component_spec.rb
spec/components/dashboard_programme_activity_group_section_component_spec.rb
spec/models/programmes/i_belong_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2853
* Adding in anchor id to the dashboard programme activity group to work  with dashboard progress bar

Primary I Belong - Final bug fixes

---

db/seeds/activities/community.rb
db/seeds/programme_activity_groupings/primary_certificate.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2798
- Updated some of the text in the seed file as specified in the ticket word document
- Added new activities into the programme activity groupings

PIB - Add new I Belong primary activities

---

app/helpers/external_link_helper.rb
app/views/i_belong_mailer/auto_enrolled.html.erb
app/views/i_belong_mailer/auto_enrolled.text.erb
app/views/i_belong_mailer/completed.html.erb
app/views/i_belong_mailer/completed.text.erb
app/views/i_belong_mailer/enrolled.html.erb
app/views/i_belong_mailer/enrolled.text.erb
app/views/i_belong_mailer/inactive_everything_but_access_resources.html.erb
app/views/i_belong_mailer/inactive_everything_but_access_resources.text.erb
app/views/i_belong_mailer/inactive_everything_but_increase_engagement.html.erb
app/views/i_belong_mailer/inactive_everything_but_increase_engagement.text.erb
app/views/i_belong_mailer/inactive_everything_but_understanding_factors.html.erb
app/views/i_belong_mailer/inactive_everything_but_understanding_factors.text.erb
app/views/i_belong_mailer/inactive_not_completed_any_sections.html.erb
app/views/i_belong_mailer/inactive_not_completed_any_sections.text.erb
app/views/i_belong_mailer/inactive_only_completed_one_section.html.erb
app/views/i_belong_mailer/inactive_only_completed_one_section.text.erb
app/views/i_belong_mailer/pending.html.erb
app/views/i_belong_mailer/pending.text.erb
spec/helpers/external_link_helper_spec.rb
spec/mailers/i_belong_mailer_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2813
- Updated I belong email copy in line with documentation in the linked ticket
- Refactored testing and added additional tests for all the links in the emails
- A few tweaks to formatting

PIB - Update I Belong auto email copy

---

db/seeds/activities/mylearning.rb
db/seeds/activities/stem_learning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2870
- The initial course seed ticket specified CP442 as an online course, but should be remote delivered CPD. Adjusted course seed files to correct this.

Corrected CP442 course seed from an online course to remote

---

db/seeds/activities/community.rb

* Review App link(s): https://teachcomputing-pr-2155.herokuapp.com/certificate/i-belong
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2856
Text updates on the activities

2856 amend copy on i belong activities

---

app/services/cms/providers/strapi/client.rb
app/services/cms/providers/strapi/factories/model_factory.rb

* Review App link(s): https://teachcomputing-pr-2157.herokuapp.com/blog/coronavirus-update
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2871
Setting featured image to return nil if not present, then adding a compact in the component to handle nil data models and just not render them

Fixing bug with missing featured images

---

app/views/new_badge_mailer/new_badge_email.html.erb
app/views/new_badge_mailer/new_badge_email.text.erb
app/views/primary_mailer/completed.html.erb
app/views/primary_mailer/completed.text.erb
spec/mailers/new_badge_spec.rb

* Review App link(s): https://teachcomputing-pr-2170.herokuapp.com/rails/mailers
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2827
- Text changes as requested by comms

Updating new mailer badge text

---

app/components/cms_page_title_component.rb
app/components/datepicker_component.rb
app/components/datepicker_component/datepicker_component.html.erb
app/components/datepicker_component/datepicker_component.scss
app/controllers/courses_controller.rb
app/helpers/courses_helper.rb
app/services/achiever/course/age_group.rb
app/services/achiever/course_filter.rb
app/views/courses/_aside-filters.html.erb
app/views/courses/programme_courses.html.erb
app/webpacker/stylesheets/components/courses/_aside_filters.scss
config/routes.rb
spec/requests/courses/programme_courses_spec.rb
spec/services/achiever/course_filter_spec.rb
spec/views/courses/_aside-filters.html_spec.rb
spec/views/courses/programme_courses.html_spec.rb

* Review App link(s): https://teachcomputing-pr-2168.herokuapp.com/primary-certificate/courses
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2844
Created a new method in the courses controller, this will allow for pre-filtering by programme
Created a specific method for the primary courses
Added new course length filter

New programme course page

---

app/services/cms/providers/strapi/factories/component_factory.rb
spec/support/cms/providers/strapi/aside_section_response.json

* Related to https://github.com/NCCE/teachcomputing.org-issues/issues/2886
Missed the aside section rename

Fixing incorrect aside section name in factory

---

db/seeds/activities/mylearning.rb

* Related to https://github.com/NCCE/teachcomputing.org-issues/issues/2855
- Adding tap to seeds

Fixing seeds missing taps

---

app/helpers/navigation_helper.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2891
Adding in the links for the new pages, and updating text on old ones. Also moving all the cms_page_path, as eventually they will result from their, rather than from routes

Adding new links to header navigation

---

app/helpers/navigation_helper.rb

* Related to https://github.com/NCCE/teachcomputing.org-issues/issues/2866
Changing order of primary menu

Updating navigation order

---

app/views/pages/enrolment/non_gcse.html.erb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2881
- Updated copy changes on the GCSE support page inline with documentation in the ticket

Copy changes on gcse support page

---

app/services/cms/providers/strapi/utils.rb
db/schema.rb
spec/services/cms/providers/strapi/utils_spec.rb
spec/support/cms/providers/strapi/strapi_stubs.rb

* Related to https://github.com/NCCE/teachcomputing.org-issues/issues/2898
Util function that lets us specify a slug that lets us copy from simple pages to the new web page system.

Script to copy simple page to web page

---

app/views/pages/get-involved.html.erb
spec/views/pages/get-involved.html_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2890
- Updated the mailto link on the Get in touch page
- Updated testing

Change the mailto address for 'Get in touch'

---

db/seeds/activities/stem_learning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2899
- Added course seed CP509

Adding course seed CP509

---

scripts/docker-entrypoint.sh

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2903
Changed entry script to run debugger using bundle exec

Running debugger with bundle to fix issues after updates

---

db/seeds/activities/mylearning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2904
Fixing incorrectly updated seed

Fixing incorrect seed of CO220

---

db/seeds/activities/stem_learning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2907
- Added course seed CP237

Course seed CP237

---

config/initializers/omniauth.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2909
Adding stem_user_id to bypass

Add stem_user_id to info section of auth bypass

---

app/lib/inactivity_queries.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2902
Fixing the incorrect slug references in the I Belong inactivity queries

Fixing incorrect slugs in the email system

---

app/components/dashboard_certificate_component.rb
app/components/dashboard_course_component/dashboard_course_component.html.erb
app/components/dashboard_course_component/dashboard_course_component.scss
app/views/dashboard/show.html.erb
spec/views/dashboard/show.html_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2911
- Fixed margin on ncce white button
- Fixed logic on enrolment text dependant on enrolment status
- Fix to pin icon clipping

Dashboard bug fixes

---

db/seeds/activities/mylearning.rb
db/seeds/activities/stem_learning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2913
Added course seeds for CZ115D, CZ116D, CZ117D, CZ118D, CZ119D, CZ120D, CZ121D

Course seeds -  CZ115D, CZ116D, CZ117D, CZ118D, CZ119D, CZ120D, CZ121D

---

config/routes.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2916
* Removing html constraint on CMS routes as this causing errors on the open graph protocol bots

Remove html constraint to fix open graph queries

---

app/helpers/external_link_helper.rb
app/views/certificates/pathways/show.html.erb
db/seeds/activities/community.rb
db/seeds/programme_activity_groupings/secondary_certificate.rb
spec/helpers/external_link_helper_spec.rb

* Current Status: Ready for (front-end review
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2918
- Updated the text on secondary community activities
- Add sanitize to display to show the html correctly
- Created lots of external link helper methods
- Updated testing

Updating the secondary activities

---

db/seeds/activities/mylearning.rb
db/seeds/activities/stem_learning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2927
- Changing course seed CZ115D from online to remote

Fix course seed on CZ115D

---

app/components/community_evidence_submission_modal_component/community_evidence_submission_modal_component.html.erb
db/seeds/activities/community.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2928
Fixing incorrect html tag in seed
Adding in sanitize for evidence

Fixing issues in secondary activities

---

app/components/user_programme_course_bookings_with_asides_component.rb
app/webpacker/stylesheets/components/cms/_shared.scss
db/seeds/activities/community.rb
db/seeds/pathways/secondary_certificate.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2929
- Aligning the public_copy_description and regular description
- Adding an include to clear a bullet warning
- Removing defunct activity from pathway

Fixing activity issues

---

db/seeds/activities/stem_learning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2932
- Added course seed CP522

Course seed CP522

---

app/controllers/auth_controller.rb

* Closes [#2938](https://github.com/NCCE/teachcomputing.org-issues/issues/2938)
- Adding in additional sentry context for when a user is logged in, to help debug any logging in issues

Adding additional context to the auth callback to help debug issues

---

db/seeds/activities/stem_learning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2939
- Added course seed CP519

Course seed - CP519

---

.env.defaults
Dockerfile
Gemfile
Gemfile.lock
config/initializers/rack_attack.rb
db/schema.rb
spec/requests/reject_unproxied_requests_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2962
- Updating Cloudflare-rails
- It now has a simple method to check if the request was from cloudflare, so we have simplified the initialiser and the testing

2962 fixing rack attack issues in rails 7 upgrade

---

app/components/cms/enrichment_component.rb
app/components/cms/enrichment_list_component/enrichment_list_component.html.erb
spec/components/cms/enrichment_list_component_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2964
- Fixing incorrect controller references

Enrichment filter bug fix

---

app/services/cms/providers/strapi/queries/enrichment_list.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2967
-  Adds missing attributes on enrichment

Adding missing fields to Enrichment List

---

app/components/location_search_results_component/location_search_results_component.html.erb
app/components/no_courses_component.rb
app/components/no_courses_component/no_courses_component.html.erb
app/controllers/courses_controller.rb
app/helpers/courses_helper.rb
app/services/achiever/course_filter.rb
app/views/courses/_aside-filters.html.erb
app/views/courses/_courses-list.html.erb
app/views/courses/index.html.erb
config/routes.rb
spec/components/location_search_results_component_spec.rb
spec/components/no_courses_component_spec.rb
spec/services/achiever/course_filter_spec.rb
spec/views/courses/_aside-filters.html_spec.rb
spec/views/courses/_courses-list.html_spec.rb
spec/views/courses/index.html_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2945
- Removed hubs from course filters
- Added redirect to course page for any legacy links
- Updated tests

Removed hubs from course filters

---

app/views/certificates/i_belong/_achievement_list.html.erb
db/seeds/programme_activity_groupings/i_belong.rb
spec/views/certificates/i_belong/show_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2978
- Fixing layout issue caused by badge removal

Fixing i belong dashboard since badge removal

---

db/seeds/activities/mylearning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2976
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2977
- Course seeds added: CO247, CO454, CO003, CO409, CO404, CO007, CO457, CO292, CO407, CO486, CO455
- Updated to always on true: CO040, CO042, CO207, CO220, CO700

New course seeds and updates to exsiting

---

db/seeds/activities/mylearning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2984
- Added course seeds CO403, CO417

Course seeds - CO403, CO417

---

lib/generators/strapi/component_generator.rb
lib/generators/strapi/component_templates/mapping_test_template.rb.tt
lib/generators/strapi/component_templates/query_template.rb.tt
spec/lib/generators/strapi/component_generator_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/3010
- Adding test mapping
- Fixing incorrect name reference in query file
- Improving testing

Improving Strapi Component generator

---

db/seeds/activities/mylearning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/3005
Added course seeds:
- CO411
- CO237
- CO440
- CO248
- CO444
- CO240
- CO005
- CO008
- CO418
- CO456
- CO461
- CO441
- CO469
- CO505
- CO413
- CO442
- CO501
- CO503
- CO512
- CO223
- CO238
- CO428
- CO463
- CO517
- CO518
- CO462
- CO466
- CO459
- CO465
- CO460
- CO467

Course seeds

---

db/seeds/programme_activity_groupings/primary_certificate.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/3014
Making primary programme cluster community activity legacy

Mark clusters activity as legacy

---

app/views/secondary_mailer/enrolled.html.erb
app/views/secondary_mailer/enrolled.text.erb
config/locales/views/certificates/secondary_certificate/_achievement_list.en.yml
spec/views/certificates/secondary-certificate/show.html_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2981
- Updated secondary dashboard text
- Updated secondary enrolled email text and added explore button

Remove F-2-F References

---

db/seeds/activities/mylearning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/3022
- Changing CO512 to CO502

Updating course code

---

db/seeds/activities/mylearning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/3023
- CO411 becomes CO411B
- CO238 becomes CO438

Fixing activity codes

---

db/seeds/activities/community.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/3030
Adding paragraph to activity text

Updating activity text

---

app/components/course_component/course_component.yml
app/presenters/live_booking_presenter.rb
spec/components/course_component_spec.rb
spec/presenters/live_booking_presenter_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/3033
- Replacing the dates coming soon copy with course being updated copy

Updating no occurrence copy

---

spec/helpers/certificate_helper_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2821
- Added tests

Adding some tests to the certificate helper

---

app/components/community_evidence_submission_modal_component/community_evidence_submission_modal_component.html.erb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/3035
- Fixing broken class

Fixing broken chevron class on rejected evidence button

---

spec/factories/activities.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/3036
Moving the STEM activity code to start from 1000, as this should stop it colliding with tests where specific codes are used to match to smart connector values, this should hopefully stop flaky test issues

Update Activity Factory

---

app/controllers/cms_controller.rb
app/services/cms/models/contains_cached.rb
app/services/cms/models/dynamic_components/blocks/horizontal_card_with_asides.rb
app/services/cms/models/dynamic_components/blocks/numbered_icon_list.rb
app/services/cms/models/dynamic_components/blocks/primary_glossary_table.rb
app/services/cms/models/dynamic_components/blocks/question_and_answer.rb
app/services/cms/models/dynamic_components/blocks/secondary_question_bank.rb
app/services/cms/models/dynamic_components/blocks/text_with_asides.rb
app/services/cms/models/dynamic_zones/dynamic_zone.rb
app/services/cms/models/has_asides.rb
app/services/cms/providers/strapi/mocks/dynamic_components/blocks/text_with_asides.rb
app/services/cms/resource.rb
spec/requests/cms/cms_web_page_spec.rb
spec/services/cms/models/contains_cached_spec.rb
spec/services/cms/resource_spec.rb
spec/support/cms/providers/strapi/strapi_stubs.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2876
Creating new ContainsCached module in the Cms to help control model that have cache items inside
Provides a way to handle cache clearance in a smarter way, other than just wiping out whole cache containers (which didnt work anyway, as memcache will not allow wildcarded cache clears)

CMS Caching Updates

---

app/views/i_belong_mailer/enrolled.html.erb
app/views/i_belong_mailer/enrolled.text.erb
app/views/i_belong_mailer/inactive_not_completed_any_sections.html.erb
app/views/i_belong_mailer/inactive_not_completed_any_sections.text.erb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/3052
- Updated the copy in two of the I belong mailers to remove references to the mode of delivery on courses

I belong mailers copy changes

---

app/views/courses/index.html.erb
app/webpacker/stylesheets/components/courses/_courses.scss
spec/views/courses/index.html_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/3063
- Updated the page title from partial to our standard page title component to be more consistent with the TC design
- Moved/refactored the intro text and aside at the top of the page to remove a big chunk of unnecessary spacing

Tidy up courses page

---

db/seeds/activities/stem_learning.rb

Adding course seed CP020.
https://linear.app/stem-learning/issue/ENG-183/course-seed-cp020

Adding course seed CP020

---

db/seeds/activities/mylearning.rb

Add course seed CO018
