NCCE/teachcomputing.org

app/views/curriculum/units/_lessons.html.erb
spec/views/curriculum/units/_lessons_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2239
*Switches to us h3 instead of just a p tag*

Edit title to use h3 tag instead

---

.env.defaults
Gemfile.lock
docker-compose.yml

* Discovered a recent change to define the `ENV_FILE` var under `environment` in the `docker-compose.yml` caused the var not to be detected, when providing a fallback in `env_file`, perhaps they're not loaded early enough? this fixes that
* Ensure `ENV_FILE=.env` is defined in your `.env` if using one

Fix for vars in .env not being picked up

---

.env.defaults
.env.test
spec/support/achiever/achiever_stubs.rb

also update the stubs for spec/services/achiever/request_spec.rb for consistency
~- [ ] Browser tested~
~- [ ] Front-end review completed~
If you don't already have this value in `.env` then restart your docker containers with `yarn run stop` and `yarn run start` to pick up the new value.

Update the default dev/staging endpoint for Achiever Smart Connector

---

.env.defaults
README.md
app/services/achiever/connection.rb
docker-compose.yml

~- [ ] Browser tested~
~- [ ] Front-end review completed~
Storm doesn't have a proxy tunnel, as we share a fixed IPv4 address, so I removed PROXY_URL from the compose file, to allow this setting in the local `.env` to override it
I moved this value to `.env.defaults` so that the proxy still works for the RPF devs that need it.
I tested by running an achiever rake task in the web container's console:
```
root@9ae610137ec9 /app - (fix/default-smart-connector-host) $ bin/rails achiever:get_course_info
false
false
false
false
false
Achiever currently has 170 courses with 1 F2F & 0 online occurrences
Time: 3.836331785 s.
root@9ae610137ec9 /app - (fix/default-smart-connector-host) $
```

Fix access to Achiever Smart Connector from a docker container without a proxy

---

app/views/pages/gender-balance.html.erb
spec/views/pages/gender-balance.html_spec.rb

* Current Status: WIP / Ready for review
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2291
* Removes newsletter call to action from gbic page
* N/A

2291: Remove gbic cta

---

config/initializers/sentry.rb

Environments can then optionally set `SENTRY_CURRENT_ENV` to a value (eg. `review`, `staging`, `qa`, `production`) in order to more clearly delineate where error reports are coming from.

Allow Sentry to be passed an environment ENV var

---

app/views/components/_announcement.html.erb
app/views/layouts/_base.html.erb
app/webpacker/stylesheets/application.scss
app/webpacker/stylesheets/components/_announcement.scss
spec/views/components/pending_announcement_spec.rb

* Adds an empty announcement container, but comments out the render
* N/A

Add empty announcement component

---

.env.defaults
db/seeds.rb
db/seeds/activities/preprod_achiever_courses.rb

* Current Status: WIP
* Review App link(s): https://qa.teachcomputing.org/courses
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2279
3 new online courses seeded as activities, only when 
```
PREPROD_ACHIEVER_COURSES=on
```
We added this variable to terraform for QA: https://github.com/NCCE/terraform/pull/178

Seed preprod QA courses

---

db/seeds/activities/mylearning.rb

a non-unique FL uuid stopped it from saving
fixed an activity seed
note that I have already manually added this record in production
is https://teachcomputing.org/courses/CO217/programming-with-guis

Fix seed for CO217 Moodle course

---

.env.defaults
.env.test
Gemfile
Gemfile.lock
app/services/feature_flag_service.rb
lib/tasks/partners.rake
spec/rails_helper.rb
spec/services/feature_flag_service_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2282
* https://github.com/NCCE/terraform/pull/179 deploys the env vars
When NCCE2 starts, turn off
- FutureLearn::CourseRunsJob
- FutureLearn::UpdateOrganisationMembershipsJob
Set
```
FLAG_NCCE2=on
NCCE2_START_DATE='2023-04-02'
```
in production when you are ready

Turn off FutureLearn update jobs on a specified date

---

app/components/provider_logos_component.rb
app/components/provider_logos_component/provider-logos_component.scss
app/components/provider_logos_component/provider_logos_component.html.erb
app/components/provider_logos_component/provider_logos_component.yml
app/models/achievement.rb
app/views/courses/_aside-booking.html.erb
app/views/dashboard/_achievement_list.html.erb
app/webpacker/stylesheets/components/courses/_aside_booking.scss
previews/components/provider_logos_component_preview.rb
spec/components/provider_logos_component_spec.rb

* Current Status: Ready for front-end & tech review
* Review App link(s): https://teachcomputing-pr-1690.herokuapp.com/dashboard
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2312
- Update provider logos and copy in the dashboard course list items
- Rm time and emphasis from dashboard online course start date

Dashboard - update logos and copy of online course (stem-learning provider only) and remove logos for FutureLearn course

---

app/components/course_activity_component/course_activity_component.html.erb
app/components/course_activity_component/course_activity_component.scss
app/models/activity.rb
app/views/certificates/primary_certificate/_achievement_list.html.erb
app/views/certificates/secondary_certificate/_achievement_list.html.erb
config/locales/views/certificates/pathways/_recommended_courses.en.yml
config/locales/views/certificates/primary_certificate/_achievement_list.en.yml
config/locales/views/certificates/secondary_certificate/_achievement_list.en.yml
db/seeds/programme_activity_groupings/primary_certificate.rb
db/seeds/programme_activity_groupings/secondary_certificate.rb
spec/views/certificates/primary-certificate/show.html_spec.rb
spec/views/certificates/secondary-certificate/show.html_spec.rb

* Current Status: Ready for front-end & tech review
* Review App link(s): *not yet deployed*
* https://qa.teachcomputing.org/certificate/secondary-certificate (note: need to have completed the accelerator and enroled)
* https://qa.teachcomputing.org/certificate/primary-certificate (note: need to have enroled)
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2287
Simplify primary and secondary certificates to require only 1 eligible course rather than 1 of each kind (live and online)
- https://docs.google.com/document/d/1rifqkHlOsnS8iRv3pKM9dCuAqc53jaRT/edit
- https://docs.google.com/document/d/1tVxTLG6vBzir5rO0vRwSvMCwlnEKFCUh/edit
Run
```
heroku run  bin/rails update_certificate_data && bin/rails db:seed --app=teachcomputing-production
```

Feature: only one course for certs

---

app/components/community_activity_component/community_activity_component.html.erb
app/components/community_activity_component/community_activity_component.scss
app/components/course_activity_component/course_activity_component.scss
app/views/layouts/activity_component_preview.html.erb
previews/components/community_activity_component_preview.rb
previews/components/course_activity_component_preview.rb

* https://teachcomputing-pr-1708.herokuapp.com/certificate/primary-certificate
* https://teachcomputing-pr-1708.herokuapp.com/rails/components/course_activity_component/default
* https://teachcomputing-pr-1708.herokuapp.com/rails/components/community_activity_component/default
* https://teachcomputing-pr-1708.herokuapp.com/rails/components/community_activity_component/completed
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2340 
CommunityActivityComponent
1. Widen button to match longest text 'Submit evidence', and change alignment of objective text, to stop button from overlapping longest objective text
2. Fix vertical alignment of button
(note that we also add a container for the 'Completed' badge to …

Fix layout bugs in primary and secondary cert dashboards

---

lib/tasks/hubs.rake

* Related to https://github.com/NCCE/teachcomputing.org-issues/issues/2351
Change name and subdeliverer_id form Leicester computing hub
This is already done in production (with Administrate), but will be handy for re-populating staging and dev environments (it is the rake task `rails hubs:populate_hubs`).

Change computing hub name to Leicestershire, Nottinghamshire and Rutland

---

app/views/pages/primary-senior-leaders.html.erb
config/environments/development.rb
config/environments/test.rb

* Review App link(s): https://teachcomputing-pr-1710.herokuapp.com/primary-senior-leaders
When removing the old FutureLearn code I needed to check that I hadn't broken any translations, so I turned on raising errors. I recommend keeping this on to catch regressions early.
I found these missing translations on the Primary Senior Leaders page, which were easily fixed by removed the options that used them.

Fix missing translation errors

---

app/helpers/navigation_helper.rb

* Current Status: Ready for front-end and tech review
* Review App link(s): https://teachcomputing-pr-1722.herokuapp.com/
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2369
New menu entry, links to Ghost CMS page https://teachcomputing.org/computing-clusters/
Large:
Small:

Link computing-clusters embedded Ghost page

---

spec/requests/pages/home_news_spec.rb

* Related to https://github.com/NCCE/teachcomputing.org-issues/issues/2374
Regression test for desired HTTP header

2374 Add spec for X-Content-Type-Options: nosniff response header

---

app/controllers/admin/application_controller.rb
app/controllers/application_controller.rb
app/controllers/certificates/certificate_controller.rb
app/controllers/certificates/cs_accelerator_controller.rb
app/controllers/certificates/primary_certificate_controller.rb
app/controllers/concerns/http_headers.rb
app/controllers/courses_controller.rb
app/controllers/dashboard_controller.rb
app/controllers/diagnostics/base_controller.rb
spec/factories/programme_activity_groupings.rb
spec/requests/admin/root_spec.rb
spec/requests/certificates/certificate_spec.rb
spec/requests/certificates/cs_accelerator/complete_spec.rb
spec/requests/certificates/cs_accelerator/show_spec.rb
spec/requests/certificates/primary_certificate/complete_spec.rb
spec/requests/certificates/primary_certificate/pending_spec.rb
spec/requests/certificates/primary_certificate/show_spec.rb
spec/requests/courses/show_spec.rb
spec/requests/dashboard/show_spec.rb
spec/requests/diagnostics/class_marker/cs_accelerator/show_spec.rb
spec/requests/diagnostics/cs_accelerator/show_spec.rb
spec/requests/diagnostics/cs_accelerator/update_spec.rb
spec/requests/pages/home_news_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2375
[Add cache-control: no-store header to private user-facing pages](https://github.com/NCCE/teachcomputing.org/commit/f6c49c2eba3af167d05ab60a9cd544a4ea699287)
including:
certificates
course show pages (that show enrolment when logged in)
dashboard
diagnostics
[Add cache-control: no-store header to admin pages](https://github.com/NCCE/teachcomputing.org/commit/a81d3df10be564ec511608601a45a444e7a5c755)
Header for these pages changes from
```
Cache-Control: max-age=0, private, must-revalidate
```
to
```
Cache-Control: no-store, must-revalidate, private, max-age=0
```
Also add a basic request spec for primary certificate show page (enrolled state) increasing coverage by 0.5%
[Add …

2375 cache control: no store HTTP header on private pages

---

app/jobs/achiever/fetch_users_completed_courses_from_achiever_job.rb

* Related to 
- https://github.com/NCCE/teachcomputing.org-issues/issues/2398
- https://github.com/NCCE/teachcomputing.org-issues/issues/2334
- Fix misleading source metadata from background job in pending certificate to improve debugging
(this data is stored in Postgres as JSON in `UserProgrammeEnrolmentTransition#metadata` )

Fix source metadata from background job in pending certificate

---

app/services/achiever/course/template.rb
app/views/certificates/pathways/_recommended_courses.html.erb
spec/services/achiever/course/template_spec.rb

* Current Status: WIP
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2421
~Rescue~ Handle and report missing course template on cert dashboard
when recommended course doesn't match a real or stubbed template
This should make dev, review and staging environments more stable, and will also help if there is ever missing data in production Dynamics.

Rescue and report missing course template on cert dashboard

---

db/seeds/activities/stem_learning.rb

* Related to #1765 and https://github.com/NCCE/teachcomputing.org-issues/issues/2445
These reflect changes in the production database I made on Friday 18 Aug 2023 via Administrate, so they won't actually change the production data. However they ensure any fresh databases such as our dev and review apps are consistent, per the business's requirement to keep seeds in sync with any live changes to the database.
Background is that new courses CP478 and CP439 were added on 18 Aug in commit 1c1075e0 (#1765):
> They are the same with the older courses which we have added W at
> the end of. What the programme team came up was that the courses are
> more under Secondary as against CSA. But IT Support has advised that
> it is best to keep the course in order …

Update seeds for CP478W and CP439W as these courses are retired

---

app/helpers/application_helper.rb
config/environments/development.rb
config/initializers/sidekiq.rb
docker-compose.yml
scripts/docker-entrypoint.sh

Previously, the docker setup used a seperate sidekiq and webpack container. "web" "sidekiq" and "webpack" all use the same dockerfile so it makes no sense to have these running on seperate containers.
This Commit, combines them into just one container called "web". It also adds "teachcomputing.test" into the list of safe redirect URLs to help puma-dev users have a more realistic environment

Alter docker configuration to use just one "web" container.

---

db/seeds/pathways/primary_certificate.rb
db/seeds/pathways/secondary_certificate.rb
db/seeds/pathways_helper.rb

This PR removes CO040, CO042, and CO230 from the pathways as they are yet to be added to dynamics.

Removed unrelased CPDs from new pathways

---

db/seeds/programme_activity_groupings/i_belong.rb

This issue occurred due to a change in how we fetch community / non-community groups.
This commit, fixes the problem by correctly flagging them

Marking i belong community groups correctly as groups

---

app/controllers/pages_controller.rb
app/views/dashboard/_enrolment-status.html.erb
config/brakeman.ignore
spec/views/dashboard/certificates/_secondary.html_spec.rb

* Review App link(s): https://teachcomputing-pr-1806.herokuapp.com/dashboard
- Altered copy from "find out more" to "choose a pathway"
- Removed excess `.includes()`

Altered copy from "find out more" to "choose a pathway"

---

app/jobs/certificate_pending_transition_job.rb
app/models/programme.rb
app/models/programmes/cs_accelerator.rb
app/models/programmes/i_belong.rb
app/models/programmes/primary_certificate.rb
app/models/programmes/secondary_certificate.rb
spec/models/programme_spec.rb
spec/models/programmes/cs_accelerator_spec.rb
spec/models/programmes/i_belong_spec.rb
spec/models/programmes/primary_certificate_spec.rb
spec/models/programmes/secondary_certificate_spec.rb

Adds a method which contains the length of time that a UPE should be pending and makes IB 14 days

Increase the delay of the IB programme pending state

---

db/seeds/activities/community.rb

* Review App link(s):
- https://teachcomputing-pr-1817.herokuapp.com/certificate/pathways/specialising-or-leading-2 (logged out)
- https://teachcomputing-pr-1817.herokuapp.com/certificate/pathways/developing-in-the-classroom-2 (logged out)
- https://teachcomputing-pr-1817.herokuapp.com/certificate/primary-certificate (logged in)
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2484
- [N/A] Tech review completed
Updates the seed of an activity to match new copy.
The "Participate fully in an NCCE curriculum enrichment opportunity" ticket should have new copy on the /certificate/primary-certificate and on both the pathway pages /certificate/pathways/specialising-or-leading-2 and …

Updated primary activity copy

---

app/components/progress_bar_component.rb
app/components/progress_bar_component/progress_bar_component.html.erb
app/lib/programme_objectives/programme_completion_required.rb
app/lib/programme_objectives/readme.md
app/models/programme.rb
app/models/programme_activity_grouping.rb
app/models/programmes/secondary_certificate.rb
app/views/certificates/i_belong/_achievement_list.html.erb
app/views/certificates/primary_certificate/_achievement_list.html.erb
app/views/certificates/secondary_certificate/_achievement_list.html.erb
spec/components/progress_bar_component_spec.rb
spec/factories/programme_activity_groupings.rb
spec/lib/programme_objectives/programme_completion_required_spec.rb
spec/models/programme_activity_grouping_spec.rb
spec/models/programme_spec.rb
spec/models/programmes/secondary_certificate_spec.rb
spec/requests/certificates/secondary_certificate/show_spec.rb
spec/support/shared_examples/plays_programme_objective_progress_bar_role.rb
spec/support/shared_examples/plays_programme_objective_role.rb
spec/views/certificates/secondary-certificate/show.html_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2496 https://github.com/NCCE/teachcomputing.org-issues/issues/2492
This PR adds the CSA as an item in the progress bar at the top of the secondary programme dashboard.
We've added a handful of new programmes to T/C now and I've held off "drying" up the code as each of the programmes has had a quite distinct set of requirements for completion. In this PR, I've started an abstraction which should let us get rid of having multiple programme controllers, and move to having just one generic controller in the future.
It's clear that we have many different completion requirements for each …

Added CSA to secondary computing dashboard.

---

app/jobs/kick_off_emails_job.rb
app/models/programme.rb
app/services/achiever/course/template.rb
config/routes.rb
db/seeds/programmes/a_level.rb
spec/factories/programmes/a_level.rb
spec/models/programmes/a_level_spec.rb
spec/requests/certificates/a_level_dashboard_spec.rb
spec/views/certificates/a_level/complete_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2502
Review will involve exploring all a-level related dashboard pages
Renamed the slug from 'a-level' to 'a-level-certificate'
I've chosen to not rename the Programmes::ALevel class or other methods from "a_level" to "a_level_certificate" as I felt it was excessive.

Change slug from a-level to a-level-certificate

---

app/models/achievement.rb
spec/models/achievement_spec.rb

Checks that an achievement belongs to cs accelerator before auto enrolling

Fixing CSA auto enrolling eagerly

---

config/routes.rb

* Review App link(s):
- https://teachcomputing-pr-1887.herokuapp.com/cs-accelerator
- https://teachcomputing-pr-1887.herokuapp.com/certificate/cs-accelerator
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2563
Added redirects so old links will still work

Added redirects from cs-accelerator to subject-knowledge

---

.circleci/config.yml

* Review App link(s): N/A
Moves standardrb into its own workflow so the tests can pass independently and there is a clearer indicator of what failed

Move standardrb to report seperatly

---

app/components/site_search_component/site_search_component_controller.js
app/controllers/searches_controller.rb

that doesn't exist
- Changes searches_controller to handle a pagy overflow error correctly
- Changes site search component to remove page query param

Fix issue with site search throwing error when you visit page

---

app/components/course_component.rb
app/components/course_component/course_component.html.erb
app/helpers/programmes_helper.rb
app/lib/searchable_site_pages.rb
app/models/programme.rb
app/models/programmes/a_level.rb
app/models/programmes/cs_accelerator.rb
app/models/programmes/i_belong.rb
app/models/programmes/primary_certificate.rb
app/models/programmes/secondary_certificate.rb
app/services/achiever/course/template.rb
app/services/achiever/course_filter.rb
app/views/dashboard/_achievement_list.html.erb
app/webpacker/stylesheets/components/_tags.scss
spec/components/course_component_spec.rb
spec/factories/achiever/course_template.rb
spec/helpers/programmes_helper_spec.rb
spec/lib/searchable_site_pages_spec.rb
spec/models/programme_spec.rb
spec/models/programmes/a_level_spec.rb
spec/models/programmes/cs_accelerator_spec.rb
spec/models/programmes/i_belong_spec.rb
spec/models/programmes/primary_certificate_spec.rb
spec/models/programmes/secondary_certificate_spec.rb
spec/requests/courses/index_spec.rb
spec/services/achiever/course/template_spec.rb
spec/services/achiever/course_filter_spec.rb

* Current Status: Ready for Tech/Front end review
* Review App link(s): https://teachcomputing-pr-1901.herokuapp.com/
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2569
Created new mapping of dynamic programme names to programme slugs
Updated by certificate filtering
Adding certificate names to programmes
Unifying the tag code into one helper method
Updates of scss class names

Updating programme mapping to allow for new tag names

---

app/services/curriculum_client/request.rb
spec/requests/curriculum/lessons/show_spec.rb
spec/services/curriculum_client/request_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2567
Added rescue for FaradayServerErrors
Made both error types report to sentry
There was an attempt to inject code into the URL of the curriculum pages, these injections caused the Curriculum GraphQL server to respond with Graphlient::Errors::FaradayServerError. We have decided to have those errors instead return a 404 error rather than passing down the 500 to the end user. These errors will be logged to Sentry so we can continue to monitor for any future issues.

Improve error handling for curriculum

---

app/models/programmes/i_belong.rb
spec/views/certificates/i_belong/complete_spec.rb

This is a temp fix, so have commented out and skipped associated tests with the intention to reinstate in the near future
Removes the auto setting of school name on certificate during I Belong completion. Method is left blank to prevent it calling the parents version. This then enables the old work flow where it will ask the user to provide a school name on first generation of the certificate

Removing auto completion of school name for i_belong

---

app/jobs/badge_assignment_check_job.rb
app/jobs/issue_badge_job.rb
app/models/programme.rb
app/models/programmes/cs_accelerator.rb
app/services/credly/badge.rb
spec/jobs/badge_assigment_check_job_spec.rb
spec/models/programmes/a_level_spec.rb
spec/models/programmes/cs_accelerator_spec.rb
spec/models/programmes/primary_certificate_spec.rb
spec/support/credly/credly_stubs.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2583
Changed the API call to credly, the email version seems to give inconsistent results, current working theory is it takes time for that search to become active as using email appears to initially fail, but then later returns result. Using the issuer_earner_id seems to not have the same issue. I believe this should help resolve the 422 errors we get when issuing badges, which might also account for the small number of missing badges.
I swapped the ordering of checks in the IssueBadgeJob, so that it checks locally if the user meets the badge requirements before it checks credly, seems more logical to check DB before making API call.
Found a bug in the …

Fixing issues in badge assignment

---

app/helpers/curriculum_helper.rb
app/views/curriculum/key_stages/_years.html.erb
spec/helpers/curriculum_helper_spec.rb

This will enable users to share links to a specific year.
We may want to bear in mind this GOVUK guidance that suggests against using anchor links:
> Try to avoid using anchor links in your content. Anchor links can be disorientating for some users with access needs who may have problems getting back to the previous page.
> 
> For example, screen magnifier users and those with motor function impairments. People using assistive technology may find it hard to see what they’ve missed or realise that they’ve skipped forward.
> 
> Avoid using anchor links to content on the same page. Instead, rearrange the structure of your content so that people can navigate the content more easily.
Instead of making the headings themselves the link, I've added small links beneath the headings so we can use …

Add anchor links to each year of a key stage

---

app/helpers/navigation_helper.rb
app/services/curriculum_client/queries/unit.rb
app/views/curriculum/lessons/show.html.erb
app/views/curriculum/units/_lessons.html.erb
app/webpacker/stylesheets/components/pages/_curriculum.scss
spec/support/curriculum/views/unit.json
spec/views/curriculum/lessons/show_spec.rb
spec/views/curriculum/units/_lessons_spec.rb

* Review App link(s): https://teachcomputing-pr-1915.herokuapp.com/
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2571
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2584
Adding download lesson button to the unit view. This will display the login button or the download button depending if the user is logged in or not.
Also fixing the typo I found in the header navigation

Download option for lesson files in Unit view

---

app/views/curriculum/key_stages/_years.html.erb
config/sitemap.rb

Resolves https://github.com/NCCE/teachcomputing.org-issues/issues/2592#issuecomment-1936037350
This PR removes anchor links from the key stage pages, but retains the generated IDs so the sections can be linked to externally.
It also adds these links to the sitemap

Remove links from key stage pages, but still allow external linking

---

app/controllers/certificates/cs_accelerator/auto_enrolments_controller.rb
app/controllers/certificates/i_belong/auto_enrolments_controller.rb
app/helpers/application_helper.rb
app/mailers/i_belong_mailer.rb
app/models/programmes/i_belong.rb
app/views/i_belong_mailer/auto_enrolled.html.erb
app/views/i_belong_mailer/auto_enrolled.text.erb
config/routes.rb
previews/mailers/i_belong_mailer_preview.rb
spec/mailers/i_belong_mailer_spec.rb
spec/models/programmes/i_belong_spec.rb
spec/requests/certificates/cs_accelerator/auto_enrolment/destroy_spec.rb
spec/requests/certificates/i_belong/auto_enrolment/destroy_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2591
Enabling the auto enrolment for I Belong
Adding in the email for the I Belong programme auto enrolment, and associated tests
Created a helper method for static resources, will add ticket for removing hard code links in other places when time allows

Enable Auto enrolment for i belong programme

---

app/webpacker/stylesheets/components/pages/_careers-support.scss

Adding media query to stop image leaking out of the header

Fixing the leaking image on mobile view for careers page

---

Gemfile
Gemfile.lock

It looks like we rely on some undocumented behavior that only exists < 2.0 to get a list of cloudflare Ips.
This causes our rack attack config to fail in staging.
This reverts commit 6d5f4c3c4757400b33688dc162d835d93d5f29e6.

Revert "Bump cloudflare-rails from 1.2.0 to 5.0.1"

---

app/views/curriculum/key_stages/index.html.erb
app/views/curriculum/key_stages/show.html.erb
app/views/curriculum/lessons/show.html.erb
app/views/curriculum/units/show.html.erb
app/webpacker/stylesheets/components/_headings.scss

Previous change meant that css was being overridden by "Objectivity" style
* Possibly needs automated testing
* Closes [#2644](https://github.com/NCCE/teachcomputing.org-issues/issues/2644)
All govuk-heading-m are being assigned the incorrect font due to change a year ago that should have only effected curriculum pages. Solution was to add a `.curriculum` class to the curriculum pages and modify the scss accordingly. The Medium headers on the curriculum continue to use 'Objectivity' whereas all other medium government headers now use the default 'DM Sans'.
N/A

Change font-family css for medium headings

---

app/components/course_component/course_component.html.erb
app/services/achiever/course/template.rb
app/webpacker/stylesheets/components/courses/_courses_list.scss
spec/components/course_component_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2631
Set the value of the bool `is_new_course` on the `@course` object passed to the course component. This has been currently set to return `true` if `activity.created_at > 3.months.ago`
N/A

Add new/improved icon

---

app/webpacker/stylesheets/settings/_colors.scss
app/webpacker/stylesheets/settings/_links.scss

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2652
- Added brand-yellow colour variable
- Footer links box-shadow to brand yellow on focus

Odd colouring of focused links in the teach computing footer

---

app/assets/stylesheets/administrate/application.scss
app/assets/stylesheets/administrate/fields/state_picker.scss
app/fields/state_picker_field.rb
app/lib/programme_objectives/assessment_pass_required.rb
app/views/fields/state_picker_field/_index.html.erb

* Review App link(s): ...
* Closes [#2670](https://github.com/NCCE/teachcomputing.org-issues/issues/2670)
- Addition of traffic light system for objective completion (albeit only where objectives are tracked / used to indicate progress) to the administrate interface (/admin)

Add traffic light icons to administrate for objectives

---

app/views/fields/state_picker_field/_index.html.erb

Fix to ensure that title label can handle nil in admin interface for user programme enrolments

Fix to ensure title label can handle nil in admin

---

app/models/user.rb
spec/components/pathway_enrol_component_spec.rb
spec/factories/user_programme_enrolments.rb

* Review App link(s): Heroku doesn't seem happy to create one as of current so will populate when ready
* Closes [#2692](https://github.com/NCCE/teachcomputing.org-issues/issues/2692)
- Ensure the query for user enrolment checks that the enrolment is in a state of `:unenrolled` as well as whether the enrolment record is present in the first place.

Allow unenrolled users to re-enroll

---

app/helpers/navigation_helper.rb

* Closes [#2676](https://github.com/NCCE/teachcomputing.org-issues/issues/2676)
Updates to the navigation helper to ensure it uses URL helpers instead of hard coding them. Makes use of the `cms_page_path` helper which, although has cms in the name, should still catch any page slugs

Add url helpers to navigation helper urls

---

app/dashboards/assessment_attempt_dashboard.rb
app/fields/assessment_details_field.rb
app/views/fields/assessment_details_field/_index.html.erb
app/views/fields/assessment_details_field/_show.html.erb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2722
- Updated the Admin UI for Assessment Attempts to include information on the assessment:
-- Assessment name
-- When assessment was created
-- When attempt state was last transitioned
-- Attempt percentage score

Update interface for assessment attempts on user view in Adminstrate 

---

app/models/programme_activity_grouping.rb
db/seeds/programme_activity_groupings/i_belong.rb

* Current Status: WIP
* Review App link(s): ...
* Closes [#2712](https://github.com/NCCE/teachcomputing.org-issues/issues/2712)
Moved the affected activity with title "Implement selected key stage 3 Teach Computing Curriculum resources" from its original programme activity grouping (which places it under section 2 in the UI) to its second programme activity grouping (placing it under 3 in the UI). Script then updates the `required_for_completion` attribute on the original grouping from 3 to 2.
- Run the method on `ProgrammeActivityGrouping.move_i_belong_section_from_2_to_3` to perform the above changes
- Remove this method in a separate PR

Move "Implement selected key stage 3 Teach Computing Curriculum resources" from section 2 to 3

---

app/models/programme_activity_grouping.rb
app/views/certificates/i_belong/_achievement_list.html.erb
db/seeds/programme_activity_groupings/i_belong.rb

* Review App link(s): https://teachcomputing-pr-2074.herokuapp.com/
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2730
Curriculum activity should now be at the top of the list
No activities should be in the drop down
Removed code needed to complete the migration as no longer needed

Fixing I Belong activities list after migration to new config

---

app/components/gov_grid_row_component.rb
app/components/gov_grid_row_component/gov_grid_row_component.html.erb
app/helpers/application_helper.rb
app/views/pages/careers-support.html.erb
previews/components/gov_grid_row_component_preview.rb
spec/components/gov_grid_row_component_spec.rb
spec/helpers/application_helper_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2660
Can review component at https://teachcomputing-pr-2080.herokuapp.com/rails/components
We have tested this on the page https://teachcomputing-pr-2080.herokuapp.com/careers-support
- Creating a new component that means the grid row code is no longer hard coded into the system
- Creates new methods to create padding and margin classes programmatically, rather than classes being hard coded

New ViewComponent for Grid Row

---

config/initializers/omniauth.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2778
- Removed the use of the Rails Boolean casting method, instead we will just do a simple string comparison for the word true (lowercase) otherwise we will assume no bypass exists
- This is due to the call to this (outside of class in the omniauth initialiser) seems to intermittently cause the app to crash out, my guess is that sometimes it takes longer to boot rails and the initialiser is being run before the library code is loaded
- I have modified the second reference (inside the class) to keep consistency in the check methods, but that one doesnt appear to cause us an issue

Remove reference to ActiveModel boolean cast in initializer

---

app/models/achievement.rb
spec/models/achievement_spec.rb

* Resolves https://github.com/NCCE/teachcomputing.org-issues/issues/2788
Moving auto-enrol call back to after_commit, as per recommendation from sidekiq to deal with race conditions [sidekiq notes](https://github.com/sidekiq/sidekiq/wiki/FAQ#why-am-i-seeing-a-lot-of-cant-find-modelname-with-id12345-errors-with-sidekiq)

Moving auto-enrolment to after_commit

---

app/views/pages/careers-support.html.erb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2805
- Updated link on the careers support page as it was going to a 404 page

Broken link on careers support page

---

app/components/cms_rich_text_block_component.rb
spec/components/cms_rich_text_block_component_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2839
- Fixing the problem with number lists not showing the numbers due to missing class

Adding in govuk class for numbered lists

---

app/components/community_activity_component.rb
app/components/community_activity_component/community_activity_component.html.erb
app/components/community_activity_component/community_activity_component.scss
app/components/progress_component.rb
app/components/progress_component/progress_component.scss
app/components/progress_component/progress_component_controller.js
app/models/programme.rb
app/models/programmes/i_belong.rb
app/webpacker/javascript/controllers/community_activity_component_controller.js
db/seeds/activities/community.rb
package.json
spec/models/programme_spec.rb
spec/models/programmes/i_belong_spec.rb
yarn.lock

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2809
Fixes the bug in this ticket:
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2801
- Additional javascript in community activity component added to check textareas for evidence and warns the user on the last section if they are missing evidence in one of the sections
- Alongside this, added links to take the user back to that missing section
- Some javascript added into the progress component so the warning only appears on the last section
- Added minimum character requirement to the evidence boxes - set to 50. When a user starts entering their evidence a text prompt will appear to show the user how many more characters are required to be a valid …

PIB - Evidence modal character validation and user warning

---

app/components/cms_page_title_component.rb
app/components/cms_page_title_component/cms_page_title_component.html.erb
app/components/cms_page_title_component/cms_page_title_component.scss
app/services/cms/models/page_title.rb
app/services/cms/providers/strapi/factories/model_factory.rb
spec/components/cms_page_title_component_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2886
Fixing the broken reference to intro-text in page titles, after strapi rename
This has taken the subtitle off the enrichment pages, this quick fix should put them back in as will be a few days before the strapi pages go live

Bug Fix: Page subtext missing after strapi rename

---

app/components/cms_dynamic_zone_component.rb
app/components/cms_picture_card_component/cms_picture_card_component.html.erb
app/components/cms_question_and_answer_component/cms_question_and_answer_component.html.erb
app/components/cms_question_and_answer_component/cms_question_and_answer_component.scss
app/components/cms_rich_text_block_component/cms_rich_text_block_component.scss
app/services/cms/dynamic_components/linked_picture.rb
app/services/cms/models/dynamic_zone.rb
app/services/cms/providers/strapi/factories/component_factory.rb
app/services/cms/providers/strapi/factories/model_factory.rb
app/services/cms/providers/strapi/mocks/linked_picture.rb
spec/components/cms_dynamic_zone_component_spec.rb
spec/services/cms/dynamic_components/linked_picture_spec.rb
spec/services/cms/providers/strapi/component_factory_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2888
- Adding linked pictures content block for dynamics zones (only currentlly used in asides)
- Fixing font in q&a and picutre cards
- Removing margin off the last P in the rich-text-block
- Removing the spacing off the dynamic zone as it was creating issues elsewhere, and giving excessive spacing

Comms fixes for Strapi ECT pages

---

app/components/cms_icon_block_component/cms_icon_block_component.scss
app/components/icon_row_component/icon_row_component.scss

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2892
Adding bit or margin to top of icon-row
Think this was caused by removing the margin of the bottom of the last paragraph to solve the other spacing complaint

Adding top margin for spacing on icon row

---

app/components/external_link_card_component.rb
app/components/external_link_card_component/external_link_card_component.html.erb
app/components/external_link_card_component/external_link_card_component.scss
app/services/curriculum_client/queries/unit.rb
app/views/curriculum/units/show.html.erb
spec/components/external_link_card_component_spec.rb
spec/components/mixed_cards_component_spec.rb
spec/support/curriculum/curriculum_schema.json
spec/support/curriculum/responses/unit.json
spec/support/curriculum/views/unit.json
spec/support/curriculum/views/unit_alt.json
spec/support/curriculum/views/unit_with_video.json
spec/views/curriculum/units/show_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2846
- Added url links into graphql definitions
- Updated unit show page to render url links via existing components

Add more than one digital summative assessment url to a unit

---

app/components/enrolment_confirmation_component.rb
app/components/enrolment_confirmation_component/enrolment_confirmation_component.html.erb
app/components/enrolment_confirmation_component/enrolment_confirmation_component.scss
app/components/modal_component.rb
app/components/modal_component/modal_component.html.erb
app/models/programme.rb
app/models/programmes/a_level.rb
app/models/programmes/cs_accelerator.rb
app/models/programmes/i_belong.rb
app/models/programmes/primary_certificate.rb
app/models/programmes/secondary_certificate.rb
app/views/certificates/pathways/show.html.erb
app/views/layouts/two-thirds.html.erb
app/webpacker/javascript/controllers/modal_controller.js
previews/components/enrolment_confirmation_component_preview.rb
spec/components/enrolment_confirmation_component_spec.rb
spec/models/programme_spec.rb
spec/models/programmes/primary_certificate_spec.rb
spec/rails_helper.rb
spec/system/components/enrolment_confirmation_component_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2861
- Created enrolment confirmation component
- Added method onto programme model that defaults confirmation to false unless specified on the programme itself as true
- Added relevant tests and previews

Implement primary certificate enrolment confirmation

---

db/seeds/activities/stem_learning.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2914
- Moved course_video_url from course seed CP292 to CP252

Moved course video url from CP292 to CP252

---

app/views/pages/_pedagogy_asides.html.erb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2919
- Remove reference to register link

Removing old register link

---

app/models/programmes/cs_accelerator.rb
spec/models/programmes/cs_accelerator_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2923
- Updated the CS accelerator model notification code to remove the 48 hour notification period. The notification will now continue to show for the user until programme has been completed.

Improve the notification functionality

---

app/helpers/courses_helper.rb
app/views/courses/_courses-details.html.erb
spec/helpers/courses_helper_spec.rb
spec/views/courses/_courses-details.html_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2901
- Online CPD to show the course duration from duration_unit and duration the same as other course formats

Display course-specific duration for online course

---

app/components/user_programme_course_bookings_with_asides_component.rb
app/components/user_programme_course_bookings_with_asides_component/user_programme_course_bookings_with_asides_component.html.erb
spec/components/user_programme_course_bookings_with_asides_component_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2940
- New method in the user courses dashboard component to send the user to the correct course page depending on the programme
- Added additional tests in for the method

Fix links to primary course page on dashboard

---

app/components/primary_dashboard_community_activity_component/primary_dashboard_community_activity_component.html.erb
app/models/activity.rb
spec/models/activity_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2942
Creating new safe method for activities to check for public copy first, then falling back to description is not included, and also allowing for nil values (to deal with legacy objects)

Fixing description nil error on legacy activites

---

app/controllers/admin/reports_controller.rb
app/controllers/admin/users_controller.rb
app/controllers/dashboard_controller.rb
app/dashboards/achievement_dashboard.rb
app/dashboards/report_dashboard.rb
app/services/programmes/progress_query.rb
app/views/admin/reports/by_programme.html.erb
app/views/admin/reports/index.html.erb
app/views/admin/reports/report_results.html.erb
config/routes.rb
spec/factories/programme_activities.rb
spec/requests/admin/reports_spec.rb
spec/services/programmes/progress_query_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2895
New query system that allows for querying of the following parameters
- Enrolled or unenrolled
- Last interaction (active: 4 months, lapsing: 4 - 8 months, lapsed: 8+ months)
- Completed programme activity groups
Returns users that match to the query filters.

Progress Activity Query System

---

.circleci/config.yml
spec/system/certificates/primary_certificate/show_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2920
- Added system testing for primary dashboard functionality when removing and adding activities

Add system tests for primary dashboard

---

app/components/enrolment_confirmation_component/enrolment_confirmation_component.html.erb
spec/components/enrolment_confirmation_component_spec.rb

* Review App link(s): https://teachcomputing-pr-2284.herokuapp.com/
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2948
* Changing enrolment confirmation to go to certificate path rather than the dashboard

Changing enrolment button to go to certificate page

---

app/components/enrolment_confirmation_component.rb
app/components/enrolment_confirmation_component/enrolment_confirmation_component.html.erb
app/views/pages/enrolment/a_level_certificate.html.erb
app/views/pages/enrolment/i_belong.html.erb
app/views/pages/enrolment/subject_knowledge.html.erb
config/locales/views/pages/enrolment/i_belong.en.yml
spec/components/enrolment_confirmation_component_spec.rb
spec/views/pages/enrolment/a_level_certificate.html_spec.rb
spec/views/pages/enrolment/cs_accelerator.html_spec.rb
spec/views/pages/enrolment/i_belong.html_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2893
- Replaced hard coded buttons with EnrolmentConfirmationComponent on certificate pages
- Added logged_out_button_text to component
- Updated test suite to cover changes

Replace enrol buttons with view component across the site

---

app/helpers/navigation_helper.rb
config/routes.rb
config/sitemap.rb

* Review App link(s): https://teachcomputing-pr-2283.herokuapp.com/
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2950
* Removing page from header and sitemap, and then adding in redirect

Removing computing clusters page

---

spec/rails_helper.rb
spec/support/simplecov_warnings_patch.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2973
- Applying monkey patch to silence line warnings from enabling erb test coverage

Silence excessive coverage warnings

---

app/components/cms/horizontal_card_component.rb
app/components/cms/horizontal_card_component/horizontal_card_component.scss
app/components/cms/resource_card_component.rb
app/components/cms/split_horizontal_card_wrapper_component.rb
app/components/cms/split_horizontal_card_wrapper_component/split_horizontal_card_wrapper_component.html.erb
app/components/cms/split_horizontal_card_wrapper_component/split_horizontal_card_wrapper_component.scss
app/components/cms/testimonial_component/testimonial_component.html.erb
spec/services/cms/providers/strapi/queries/components/blocks/horizontal_card_spec.rb

Adding white-bg to any component that we had made hard coded white to deal with the automatic handling of text on white-bgs

Fixing white text issue

---

app/controllers/auth_controller.rb
spec/requests/auth/callback_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/3008
* Moving custom claim capture as I had it in the wrong place

Modifying the custom claim capture

---

app/components/community_activity_list_component.rb
app/models/programme_activity_grouping.rb
spec/components/community_activity_list_component_spec.rb
spec/models/programme_activity_grouping_spec.rb

* Review App link(s): https://teachcomputing-pr-2329.herokuapp.com/
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2987
- Removed the logic that discounted legacy activities from programme activity grouping
- Updated community activity list to show legacy achievements, but not the activity unless the user has started on it

Make legacy activities count towards certificate completion

---

app/views/courses/_aside-filters.html.erb
spec/system/courses/index_spec.rb
spec/views/courses/_aside-filters.html_spec.rb

* Review App link(s): https://teachcomputing-pr-2345.herokuapp.com/
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2982
- Removed Type, Date and Location filters from the front end of the search system
- We have not removed the logic, this is because their might be a need to add these filters back in in the future, and we can leave the backend logic without issue.

Removing type, date and location filter from searches

---

app/components/cms/full_width_image_banner_component.rb
app/components/cms/full_width_image_banner_component/full_width_image_banner_component.html.erb
app/components/cms/full_width_image_banner_component/full_width_image_banner_component.scss
app/services/cms/dynamic_components/blocks/full_width_image_banner.rb
app/services/cms/models/image.rb
app/services/cms/providers/strapi/factories/blocks_factory.rb
app/services/cms/providers/strapi/mocks/dynamic_components/blocks/full_width_image_banner.rb
app/services/cms/providers/strapi/queries/components/blocks/full_width_image_banner.rb
app/services/cms/providers/strapi/queries/dynamic_zone.rb
lib/generators/strapi/component_generator.rb
lib/generators/strapi/component_templates/mapping_test_template.rb.tt
previews/components/cms/full_width_image_banner_component_preview.rb
spec/components/cms/full_width_image_banner_component_spec.rb
spec/services/cms/dynamic_components/blocks/full_width_image_banner_spec.rb
spec/services/cms/providers/strapi/queries/components/blocks/full_width_image_banner_spec.rb

* Review App link(s): https://teachcomputing-pr-2351.herokuapp.com/
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2999
* New full width banner image component
* Fixed a few issues in the generator

Full Width Image Banner

---

app/components/cms/image_component.rb
app/components/cms/image_component/image_component.html.erb
app/components/cms/resource_card_component/resource_card_component.html.erb
app/components/cms/resource_card_component/resource_card_component.scss
previews/components/cms/resource_card_component_preview.rb
spec/components/cms/image_component_spec.rb
spec/components/cms/resource_card_component_spec.rb

* Review App link(s): https://teachcomputing-pr-2356.herokuapp.com/
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2998
- Changed the card to work if there was no title provided (will not show icon if no title given)
- Limited the size of the icons
- Fixed a weird class print error in the cms-image component

Make resource card title optional

---

spec/components/user_programme_course_bookings_with_asides_component_spec.rb
spec/mailers/cms_mailer_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/3016
- Fixing two tests there were being tripped up by repeated stem activity code.
- Moved the cms mailer one to a higher range to prevent collisions
- The user programme course booking, I have repeated the fix I used previously as the second one is now tripping up. These require specific keys that appear in the dynamics mocks

Fixing flaky tests

---

app/components/cpd_course_item_component.rb
app/components/cpd_course_item_component/cpd_course_item_component.html.erb
spec/components/cpd_course_item_component_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/3015
- Changed achievement check to account for multiple achievements for the same course
- If any completed, show completed flag
- if any in progress, show in progress flag,
- otherwise show book option

I Belong dashboard Fix - Dropped Activity

---

app/controllers/certificates/i_belong_controller.rb
app/controllers/certificates/secondary_certificate_controller.rb
app/models/pathway.rb
app/models/programme.rb
app/models/programmes/cs_accelerator.rb
app/models/user_programme_assessment.rb
app/view_objects/csa_dash.rb
app/views/certificates/a_level/_achievement_list.html.erb
app/views/certificates/cs_accelerator/_achievements.html.erb
app/views/certificates/cs_accelerator/complete.html.erb
app/views/certificates/cs_accelerator/show.html.erb
app/views/certificates/pathways/_recommended_courses.html.erb
app/views/components/_support-aside.html.erb
config/locales/views/a_level/_achievement_list.en.yml
config/locales/views/certificates/pathways/_recommended_courses.en.yml
spec/models/pathway_spec.rb
spec/models/programmes/cs_accelerator_spec.rb
spec/models/user_programme_assessment_spec.rb
spec/view_objects/csa_dash_spec.rb
spec/views/certificates/cs_accelerator/_achievements.html.erb_spec.rb
spec/views/certificates/cs_accelerator/complete.html_spec.rb

* Review App link(s): https://teachcomputing-pr-2354.herokuapp.com/
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/3012
Due to the move to more online courses, we needed to change the logic of the CSA exam gateway, now you need 20 credits worth of face to face (this covers the legacy option where users could do two face to face course) or 30 credits, which covers the following scenarios
- 1 face to face & 1 online (10 + 20)
- 2 online (20 + 20)
- 1 residential (40)
Dashboard has been update to reflect the single poll of options for courses, rather than required and recommended
Removed a load of old logic related to testing
While was doing this cleared the bullet warnings off dashboards relating to eager loading …

Changing CSA exam logic

---

app/components/cms/featured_blog_posts_component/featured_blog_posts_component.scss

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/3021
Making image in the featured main section 100% width on homepage

Fixing image leaking on home page

---

app/components/cms/card_wrapper_component/card_wrapper_component.html.erb
app/components/cms/course_card_component.rb
app/components/cms/course_card_component/course_card_component.html.erb
app/components/cms/course_card_component/course_card_component.scss
app/services/cms/dynamic_components/course_card.rb
app/views/achievement_mailer/completed_course.html.erb
config/routes.rb
spec/components/cms/course_card_component_spec.rb
spec/services/cms/dynamic_components/course_card_section_spec.rb

* Current Status: Ready for  tech review
* Review App link(s): https://teachcomputing-pr-2374.herokuapp.com/
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/3000
- Implemented the replaced by check on the data model for course cards
- This will replace the link and the icon information, but leave the course title and description the same
- This is intended as a temporary protection in case a course card is missed, but should be updated in Strapi to correct course instance, hence sentry notification

Adding replaced_by logic to course cards

---

app/components/benchmark_bordered_cards_component/benchmark_bordered_cards_component.html.erb
app/components/course_component/course_component.html.erb
app/components/course_component/course_component.yml
app/helpers/careers_helper.rb
app/views/courses/index.html.erb
config/sitemap.rb
spec/components/benchmark_bordered_cards_component_spec.rb
spec/components/course_component_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/3031
- Removing hubs reference from course page. 
- Also removed the text referencing the different course formats.
- Removed hubs from sitemap

Removing references to hubs and course formats from courses page

---

app/components/cms/button_block_component.rb
app/components/cms/button_block_component/button_block_component.html.erb
app/components/cms/button_block_component/button_block_component.scss
app/components/cms/resource_card_component/resource_card_component.scss
app/services/cms/dynamic_components/blocks/button_block.rb
app/services/cms/providers/strapi/factories/blocks_factory.rb
app/services/cms/providers/strapi/mocks/dynamic_components/blocks/button_block.rb
app/services/cms/providers/strapi/queries/components/blocks/button_block.rb
app/services/cms/providers/strapi/queries/dynamic_zone.rb
previews/components/cms/button_block_component_preview.rb
spec/components/cms/button_block_component_spec.rb
spec/services/cms/dynamic_components/blocks/button_block_spec.rb
spec/services/cms/providers/strapi/queries/components/blocks/button_block_spec.rb

* Review App link(s): https://teachcomputing-pr-2371.herokuapp.com/
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2985
- New button container component

Button Container

---

app/components/cms/feedback_banner_component.rb
app/components/cms/feedback_banner_component/feedback_banner_component.html.erb
app/components/cms/feedback_banner_component/feedback_banner_component.scss
app/services/cms/dynamic_components/blocks/feedback_banner.rb
app/services/cms/providers/strapi/factories/blocks_factory.rb
app/services/cms/providers/strapi/mocks/dynamic_components/blocks/feedback_banner.rb
app/services/cms/providers/strapi/queries/components/blocks/feedback_banner.rb
app/services/cms/providers/strapi/queries/dynamic_zone.rb
previews/components/cms/feedback_banner_component_preview.rb
spec/components/cms/feedback_banner_component_spec.rb
spec/services/cms/dynamic_components/blocks/feedback_banner_spec.rb
spec/services/cms/providers/strapi/queries/components/blocks/feedback_banner_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2992
- Added new cms feedback banner component and model

Strapi component - Feedback banner

---

config/sitemap.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/3011
- Changing hardcoded pagination queries in sitemap to use the all records method instead.

Using all_record in sitemap Strapi lookups

---

app/services/cms/models/collections/email_template.rb
spec/services/cms/models/collections/email_template_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/3048
- The time_diff_words method was failing tests as it assumed that months would have 30 days, but as we are now comparing back to February which only had 28 days the method needed updating to account for this.

Updating time_diff_words method to handle months that aren't 30 days

---

spec/jobs/achiever/fetch_users_completed_courses_from_achiever_job_spec.rb

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/3062
- Added additional testing for exception handling in the fetch from achiever job

Adding additional testing for exception handling

---

package.json
yarn.lock

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/3073
Pinning webpack to 4.46.0 to remove dependabot PR. Update not required at this time.

Pin webpack to 4.46.0

---

app/controllers/class_marker/webhooks_controller.rb
app/controllers/concerns/curriculum/rateable.rb
app/controllers/dynamics/webhooks_controller.rb
spec/requests/class_marker/webhook/assessment_spec.rb
spec/support/class_marker/missing_params_webhook.json

* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/3074
The following controllers were using the `request` object in the response:
- class_marker/webhooks_controller.rb
- dynamics/webhooks_controller.rb
- concerns/curriculum/rateable.rb
This is outdated and we should be using `params`.
As part of this tech debt, I've added some additional checking into the classmarker controller to ensure the required data is present before proceeding to the job.

Update controllers to use params
